import type { CityGuide } from "./types";

export const cities: CityGuide[] = [
  {
    id: "chengdu",
    name: "成都",
    province: "四川",
    tagline: "少不入蜀，老不出川",
    gradient: "from-emerald-400 via-green-300 to-amber-200",
    isNiche: false,
    destTypes: ["food_city", "city_walk", "ancient_city"],
    durationRange: "3-4d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn"],
    bestTime: "3-6月 / 9-11月",
    duration: "4-5天",
    budget: "人均1500-2500元",
    transportHub: "双流机场/天府机场/成都东站",
    coreTip: "火锅微辣是最后的温柔，别逞强点中辣",
    funSpots: [
      { name: "大熊猫繁育研究基地", tagline: "国宝零距离", ticket: "55元", duration: "3-4小时", bestTime: "7:30入园看熊猫早餐", tips: "9点后熊猫犯困，早起是关键", priority: "must" },
      { name: "人民公园鹤鸣茶社", tagline: "成都慢生活体验", ticket: "免费", duration: "2-3小时", bestTime: "下午2-5点", tips: "体验采耳+盖碗茶，最地道的成都下午", priority: "must" },
      { name: "武侯祠+锦里", tagline: "三国文化圣地", ticket: "50元(武侯祠)", duration: "3小时", bestTime: "下午逛祠傍晚逛锦里", tips: "锦里夜景比白天更美，免费进入", priority: "must" },
      { name: "青城山", tagline: "道教名山", ticket: "前山80元/后山20元", duration: "半天-1天", bestTime: "上午出发避人群", tips: "前山人文后山自然，选一个即可", priority: "niche" },
      { name: "杜甫草堂", tagline: "诗圣故居", ticket: "50元", duration: "2小时", bestTime: "上午人少清幽", tips: "浣花溪公园免费，连着逛", priority: "nearby" },
    ],
    food: [
      { name: "火锅", pricePerPerson: "80-120元", howToEat: "鸳鸯锅起手，毛肚鸭肠七上八下", pitfall: "微辣已经很够劲，外地人别逞强" },
      { name: "钵钵鸡", pricePerPerson: "30-50元", howToEat: "红油和藤椒各拿一把，冷吃最爽", pitfall: "路边摊比连锁店更有味" },
      { name: "甜水面", pricePerPerson: "10-15元", howToEat: "甜辣酱裹着粗面条，一口上头", pitfall: "洞子口张老二最正宗但排队" },
      { name: "蛋烘糕", pricePerPerson: "5-10元", howToEat: "奶油+肉松是经典，别搞太花哨", pitfall: "街边推车的比店里的香" },
      { name: "冒菜", pricePerPerson: "25-40元", howToEat: "选好菜品现煮，配米饭绝了", pitfall: "午餐性价比之王，晚上吃略腻" },
    ],
    foodAreas: [
      { name: "建设路美食街", location: "成华区建设路", bestTime: "晚餐/夜宵", direction: "小吃集中，一家家排队吃过去" },
      { name: "魁星楼街", location: "青羊区魁星楼街", bestTime: "午餐/晚餐", direction: "本地人替代宽窄巷子的去处" },
      { name: "玉林路一带", location: "武侯区玉林路", bestTime: "晚上", direction: "小酒馆+串串+烤肉，文艺又接地气" },
    ],
    shopping: [
      { name: "太古里", category: "mall", duration: "2-3小时", highlight: "低密度开放式购物，建筑本身值得逛", forWho: "购物/拍照" },
      { name: "玉林路", category: "old_street", duration: "2小时", highlight: "小酒馆和独立书店扎堆", forWho: "散步/文艺" },
      { name: "送仙桥古玩市场", category: "night_market", duration: "1-2小时", highlight: "淘旧书字画手工艺品", forWho: "淘货/散步" },
    ],
    pitfalls: [
      { category: "scenic", content: "宽窄巷子商业味重，拍照打卡即可，吃喝去魁星楼街" },
      { category: "food", content: "春熙路网红店排队久，不值得浪费旅行时间" },
      { category: "traffic", content: "出租车高峰期难打，地铁更靠谱" },
      { category: "general", content: "带肠胃药，火锅虽好不要贪杯" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["人民公园鹤鸣茶社"], afternoon: ["武侯祠+锦里"], evening: ["宽窄巷子(只逛)"], walkLevel: "约8千步", transport: "地铁+步行", nearbyFood: "魁星楼街晚餐" },
        { label: "Day2", morning: ["大熊猫基地(7:30入园)"], afternoon: ["杜甫草堂"], evening: ["玉林路小酒馆"], walkLevel: "约1.2万步", transport: "地铁+打车", nearbyFood: "玉林路串串" },
        { label: "Day3", morning: ["太古里+IFS"], afternoon: ["送仙桥古玩市场"], evening: ["建设路夜宵"], walkLevel: "约1万步", transport: "地铁+步行", nearbyFood: "建设路小吃" },
      ],
      intense: [
        { label: "Day1", morning: ["大熊猫基地(7:30入园)"], afternoon: ["杜甫草堂→浣花溪公园→送仙桥"], evening: ["宽窄巷子→魁星楼街"], walkLevel: "约1.5万步", transport: "地铁+步行", nearbyFood: "魁星楼街" },
        { label: "Day2", morning: ["武侯祠"], afternoon: ["锦里→人民公园→鹤鸣茶社"], evening: ["玉林路→建设路"], walkLevel: "约1.8万步", transport: "地铁+步行", nearbyFood: "建设路小吃街" },
        { label: "Day3", morning: ["青城山(前山)"], afternoon: ["青城山→返程"], evening: ["太古里+IFS"], walkLevel: "约2万步", transport: "高铁+打车", nearbyFood: "太古里周边" },
        { label: "Day4", morning: ["金沙遗址博物馆"], afternoon: ["文殊院→太古里补逛"], evening: ["火锅 farewell dinner"], walkLevel: "约1.2万步", transport: "地铁+步行", nearbyFood: "文殊院旁小吃" },
      ],
    },
    packingList: [
      { name: "轻薄外套", category: "clothing", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "雨伞", category: "gear", required: true },
      { name: "肠胃药", category: "medicine", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "防晒霜", category: "gear", required: false },
    ],
    nearbyFrom: ["重庆"],
    nearbyDistance: "高铁1.5小时",
    holidayWarning: "国庆/五一期间大熊猫基地排队2小时+",
    holidayAlternative: "都江堰+青城山人少得多",
  },
  {
    id: "hangzhou",
    name: "杭州",
    province: "浙江",
    tagline: "上有天堂，下有苏杭",
    gradient: "from-sky-300 via-blue-200 to-pink-200",
    isNiche: false,
    destTypes: ["ancient_city", "nature", "city_walk"],
    durationRange: "3-4d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn"],
    bestTime: "3-5月 / 9-11月",
    duration: "3-4天",
    budget: "人均1500-3000元",
    transportHub: "萧山机场/杭州东站",
    coreTip: "西湖周末人山人海，工作日去体验好10倍",
    funSpots: [
      { name: "西湖环湖", tagline: "人间天堂名片", ticket: "免费", duration: "3-4小时", bestTime: "清晨或傍晚", tips: "租自行车环湖最惬意，苏堤白堤必骑", priority: "must" },
      { name: "灵隐寺", tagline: "千年古刹", ticket: "75元(含飞来峰)", duration: "2-3小时", bestTime: "上午8点前最清净", tips: "飞来峰石刻别错过，比寺庙更值得看", priority: "must" },
      { name: "龙井茶园(梅家坞)", tagline: "茶山采风", ticket: "免费", duration: "2-3小时", bestTime: "上午采茶午后品茶", tips: "梅家坞比龙井村更原生态", priority: "must" },
      { name: "西溪湿地", tagline: "城市中的世外桃源", ticket: "80元", duration: "3-4小时", bestTime: "午后摇橹船", tips: "摇橹船比电瓶船更有意境", priority: "niche" },
      { name: "南宋御街", tagline: "千年古道", ticket: "免费", duration: "1-2小时", bestTime: "傍晚散步", tips: "串联鼓楼与中山路，可顺路逛", priority: "nearby" },
    ],
    food: [
      { name: "西湖醋鱼", pricePerPerson: "60-80元", howToEat: "酸甜口，选草鱼比鲈鱼正宗", pitfall: "楼外楼最出名但本地人更爱外婆家" },
      { name: "龙井虾仁", pricePerPerson: "80-100元", howToEat: "茶香与虾鲜搭配，配米饭", pitfall: "正规餐厅做，路边店不靠谱" },
      { name: "片儿川", pricePerPerson: "15-25元", howToEat: "笋片雪菜是灵魂，早餐来一碗", pitfall: "只有杭州才有，别拿它跟普通面比" },
      { name: "知味观小笼", pricePerPerson: "20-30元", howToEat: "鲜肉小笼先开窗后喝汤", pitfall: "总店比分店好吃" },
      { name: "葱包桧", pricePerPerson: "5-8元", howToEat: "油条+春卷皮压扁煎，蘸甜面酱", pitfall: "街边小推车的最好吃" },
    ],
    foodAreas: [
      { name: "河坊街/高银街", location: "上城区", bestTime: "午餐/晚餐", direction: "游客向但品类全，当入门级" },
      { name: "胜利河美食街", location: "拱墅区", bestTime: "晚餐/夜宵", direction: "本地人爱去，小龙虾和家常菜" },
      { name: "中山中路", location: "上城区", bestTime: "午餐", direction: "老字号聚集，面馆和小吃" },
    ],
    shopping: [
      { name: "河坊街", category: "old_street", duration: "1-2小时", highlight: "古风商业街，适合拍照打卡", forWho: "拍照/散步" },
      { name: "武林夜市", category: "night_market", duration: "1-2小时", highlight: "本地人爱逛，烟火气十足", forWho: "散步/淘货" },
      { name: "湖滨银泰in77", category: "mall", duration: "2-3小时", highlight: "西湖边的购物中心，逛完直接看湖", forWho: "购物/拍照" },
    ],
    pitfalls: [
      { category: "scenic", content: "西湖周末人山人海，工作日去体验好10倍" },
      { category: "food", content: "河坊街小吃溢价严重，看看就好别当真" },
      { category: "general", content: "龙井村买茶水极深，不懂茶别在当地买" },
      { category: "scenic", content: "断桥不断，别真去找断的地方" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["西湖(苏堤+白堤骑行)"], afternoon: ["灵隐寺"], evening: ["河坊街散步"], walkLevel: "约1万步", transport: "自行车+地铁", nearbyFood: "河坊街小吃" },
        { label: "Day2", morning: ["梅家坞品茶"], afternoon: ["西溪湿地摇橹船"], evening: ["武林夜市"], walkLevel: "约8千步", transport: "打车", nearbyFood: "胜利河美食街" },
        { label: "Day3", morning: ["南宋御街+鼓楼"], afternoon: ["湖滨银泰+西湖音乐喷泉"], evening: ["中山中路觅食"], walkLevel: "约1万步", transport: "步行+地铁", nearbyFood: "中山中路面馆" },
      ],
      intense: [
        { label: "Day1", morning: ["西湖骑行(苏堤→白堤→断桥)"], afternoon: ["灵隐寺+飞来峰→梅家坞品茶"], evening: ["河坊街→高银街"], walkLevel: "约2万步", transport: "自行车+打车", nearbyFood: "高银街" },
        { label: "Day2", morning: ["西溪湿地(摇橹船3小时)"], afternoon: ["龙井村茶山徒步"], evening: ["胜利河美食街→武林夜市"], walkLevel: "约1.8万步", transport: "打车", nearbyFood: "胜利河" },
        { label: "Day3", morning: ["浙江省博物馆→南宋御街"], afternoon: ["雷峰塔→净慈寺→花港观鱼"], evening: ["湖滨银泰+音乐喷泉"], walkLevel: "约1.5万步", transport: "步行+地铁", nearbyFood: "湖滨银泰周边" },
      ],
    },
    packingList: [
      { name: "轻薄雨衣", category: "clothing", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "雨伞", category: "gear", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    nearbyFrom: ["上海"],
    nearbyDistance: "高铁45分钟",
    holidayWarning: "国庆西湖断桥人挤人，拍照全是人头",
    holidayAlternative: "湘湖人少景美，同样是湘湖文化",
  },
  {
    id: "xian",
    name: "西安",
    province: "陕西",
    tagline: "一朝步入长安，一日读懂千年",
    gradient: "from-amber-300 via-orange-200 to-red-200",
    isNiche: false,
    destTypes: ["ancient_city", "food_city", "city_walk"],
    durationRange: "3-4d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn"],
    bestTime: "3-5月 / 9-11月",
    duration: "4-5天",
    budget: "人均1200-2000元",
    transportHub: "咸阳机场/西安北站",
    coreTip: "兵马俑一定要请讲解，不然就是看泥人",
    funSpots: [
      { name: "秦始皇兵马俑", tagline: "世界第八大奇迹", ticket: "120元", duration: "3-4小时", bestTime: "上午8点第一批进", tips: "必须请讲解！一号坑最震撼", priority: "must" },
      { name: "古城墙骑行", tagline: "13.7公里环城一圈", ticket: "54元", duration: "2小时", bestTime: "下午4-6点看日落", tips: "南门租自行车，顺时针骑一圈", priority: "must" },
      { name: "大唐不夜城", tagline: "穿越回盛唐", ticket: "免费", duration: "2-3小时", bestTime: "晚上7-10点", tips: "灯光+演出，拍照超出片", priority: "must" },
      { name: "陕西历史博物馆", tagline: "国宝仓库", ticket: "免费(需预约)", duration: "3小时", bestTime: "上午开馆即入", tips: "提前在公众号抢票，周一闭馆", priority: "niche" },
      { name: "华山大雾可改日", tagline: "西岳华山", ticket: "160元+索道", duration: "1天", bestTime: "春秋天气好时", tips: "天气不好别硬上，安全第一", priority: "nearby" },
    ],
    food: [
      { name: "肉夹馍", pricePerPerson: "10-15元", howToEat: "白吉馍夹腊汁肉，趁热吃最香", pitfall: "子午路张记最正宗，别在景区买" },
      { name: "羊肉泡馍", pricePerPerson: "30-50元", howToEat: "自己掰馍是仪式感，越小越入味", pitfall: "至少留1小时掰馍+吃，别赶时间" },
      { name: "凉皮", pricePerPerson: "8-15元", howToEat: "秦镇米皮和宝鸡擀面皮都试试", pitfall: "两种流派口感不同，都好吃" },
      { name: "biangbiang面", pricePerPerson: "20-30元", howToEat: "一根面宽如裤带，油泼最香", pitfall: "字写不出没关系，面好吃就行" },
      { name: "甑糕", pricePerPerson: "5-10元", howToEat: "红枣糯米蒸制，早餐来一份", pitfall: "早上才能买到，下午就没了" },
    ],
    foodAreas: [
      { name: "永兴坊", location: "新城区中山门", bestTime: "午餐/晚餐", direction: "非遗美食街区，比回民街干净精致" },
      { name: "北院门巷子", location: "莲湖区北院门", bestTime: "午餐/晚餐", direction: "回民街主街商业化，往巷子里走才有真美食" },
      { name: "东新街夜市", location: "新城区东新街", bestTime: "夜宵", direction: "本地人深夜觅食地" },
    ],
    shopping: [
      { name: "书院门", category: "old_street", duration: "1-2小时", highlight: "古玩字画一条街，文房四宝", forWho: "淘货/文艺" },
      { name: "永兴坊", category: "night_market", duration: "1-2小时", highlight: "非遗美食+文创", forWho: "吃货/拍照" },
      { name: "大唐西市", category: "mall", duration: "2-3小时", highlight: "丝绸之路主题商业区", forWho: "购物/亲子" },
    ],
    pitfalls: [
      { category: "scenic", content: "华清池只是洗澡的池子，期望别太高" },
      { category: "traffic", content: "火车站附近假兵马俑景区多，认准临潼区正门" },
      { category: "scenic", content: "兵马俑一定要请讲解，不然就是看泥人" },
      { category: "food", content: "回民街主街已纯商业化，往北院门巷子里走才是真美食" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["古城墙骑行(南门)"], afternoon: ["书院门→碑林博物馆"], evening: ["永兴坊晚餐"], walkLevel: "约1万步", transport: "地铁+自行车", nearbyFood: "永兴坊" },
        { label: "Day2", morning: ["兵马俑(8点出发)"], afternoon: ["大雁塔广场"], evening: ["大唐不夜城"], walkLevel: "约1.2万步", transport: "旅游专线+地铁", nearbyFood: "北院门巷子" },
        { label: "Day3", morning: ["陕西历史博物馆"], afternoon: ["小雁塔+西安博物院"], evening: ["东新街夜市"], walkLevel: "约1万步", transport: "地铁+步行", nearbyFood: "东新街" },
      ],
      intense: [
        { label: "Day1", morning: ["古城墙骑行(全程13.7km)"], afternoon: ["碑林→书院门→湘子庙街"], evening: ["回民街巷子→鼓楼市"], walkLevel: "约2万步", transport: "自行车+步行", nearbyFood: "北院门巷子" },
        { label: "Day2", morning: ["兵马俑(首批入)"], afternoon: ["华清宫→大雁塔"], evening: ["大唐不夜城→大唐芙蓉园"], walkLevel: "约2万步", transport: "旅游专线+地铁", nearbyFood: "大唐不夜城" },
        { label: "Day3", morning: ["陕西历史博物馆"], afternoon: ["小雁塔→西安博物院→永兴坊"], evening: ["钟鼓楼夜景→东新街夜市"], walkLevel: "约1.8万步", transport: "步行+地铁", nearbyFood: "东新街夜市" },
        { label: "Day4", morning: ["华山(全天)"], afternoon: ["华山→返程"], evening: ["泡馍 farewell"], walkLevel: "约2.5万步", transport: "高铁+索道", nearbyFood: "山下餐馆" },
      ],
    },
    packingList: [
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "轻薄外套", category: "clothing", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "水杯", category: "gear", required: false },
    ],
    nearbyFrom: ["郑州", "兰州"],
    nearbyDistance: "高铁2小时",
    holidayWarning: "国庆兵马俑排队3小时+，古城墙人挤人",
    holidayAlternative: "咸阳博物馆+茂陵，人少同类型",
  },
  {
    id: "chongqing",
    name: "重庆",
    province: "重庆",
    tagline: "8D魔幻之城，火锅江湖",
    gradient: "from-red-400 via-rose-300 to-purple-300",
    isNiche: false,
    destTypes: ["food_city", "city_walk"],
    durationRange: "3-4d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn"],
    bestTime: "3-5月 / 10-11月",
    duration: "3-4天",
    budget: "人均1200-2000元",
    transportHub: "江北机场/重庆北站",
    coreTip: "导航在重庆会失灵，多问路少信地图",
    funSpots: [
      { name: "洪崖洞", tagline: "千与千寻现实版", ticket: "免费", duration: "1-2小时", bestTime: "晚8-10点灯光最美", tips: "拍照不花钱，进去消费没必要", priority: "must" },
      { name: "李子坝轻轨穿楼", tagline: "8D城市奇观", ticket: "免费", duration: "30分钟", bestTime: "白天光线好时", tips: "最佳拍摄点在马路对面观景台", priority: "must" },
      { name: "长江索道", tagline: "空中看两江", ticket: "往返30元", duration: "30分钟", bestTime: "傍晚看两江交汇", tips: "单程即可，往返人更多", priority: "must" },
      { name: "山城第三步道", tagline: "老城步道", ticket: "免费", duration: "1-2小时", bestTime: "下午4-6点", tips: "俯瞰长江好角度，免费", priority: "niche" },
      { name: "磁器口古镇", tagline: "千年古镇", ticket: "免费", duration: "2小时", bestTime: "工作日上午", tips: "周末人挤人，工作日去才值得", priority: "nearby" },
    ],
    food: [
      { name: "老火锅", pricePerPerson: "80-120元", howToEat: "越偏巷子越正宗，毛肚七上八下", pitfall: "鸳鸯锅不丢人，微辣是最后的妥协" },
      { name: "小面", pricePerPerson: "8-15元", howToEat: "豌杂面是招牌，加个煎蛋", pitfall: "花市豌杂面、板凳面庄最正宗" },
      { name: "酸辣粉", pricePerPerson: "10-15元", howToEat: "好又来解放碑总店，永远排队", pitfall: "排队是值得的，别买包装版" },
      { name: "烤鱼", pricePerPerson: "50-80元", howToEat: "万州烤鱼是鼻祖，江边吃更有氛围", pitfall: "别在景区吃，去江边大排档" },
      { name: "冰粉凉虾", pricePerPerson: "5-8元", howToEat: "解辣神器，红糖水+冰粉+凉虾", pitfall: "街头小摊3元一碗最正宗" },
    ],
    foodAreas: [
      { name: "解放碑八一路", location: "渝中区八一路", bestTime: "午餐/晚餐", direction: "小吃集中，酸辣粉+冰粉一条龙" },
      { name: "南岸区弹子石老街", location: "南岸区弹子石", bestTime: "晚餐", direction: "老街+江景+美食三合一" },
      { name: "观音桥好吃街", location: "江北区观音桥", bestTime: "午餐/晚餐", direction: "本地人更爱逛的商圈美食" },
    ],
    shopping: [
      { name: "解放碑", category: "mall", duration: "2-3小时", highlight: "重庆地标，周边商圈繁华", forWho: "购物/打卡" },
      { name: "黄桷坪涂鸦街", category: "old_street", duration: "1-2小时", highlight: "川美校外涂鸦墙，文艺打卡地", forWho: "拍照/文艺" },
      { name: "观音桥", category: "mall", duration: "2-3小时", highlight: "本地人更爱逛的商圈", forWho: "购物/吃货" },
    ],
    pitfalls: [
      { category: "traffic", content: "导航在重庆会失灵，多问路少信地图" },
      { category: "scenic", content: "洪崖洞拍照不花钱，进去消费没必要" },
      { category: "scenic", content: "磁器口国庆别去，人挤人到窒息" },
      { category: "food", content: "微辣是重庆人最后的妥协，外地人点鸳鸯锅不丢人" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["李子坝轻轨穿楼"], afternoon: ["磁器口古镇"], evening: ["洪崖洞夜景"], walkLevel: "约1万步", transport: "地铁+步行", nearbyFood: "磁器口陈麻花+小面" },
        { label: "Day2", morning: ["长江索道"], afternoon: ["山城第三步道"], evening: ["解放碑+八一路"], walkLevel: "约1.2万步", transport: "地铁+步行", nearbyFood: "八一路小吃" },
        { label: "Day3", morning: ["黄桷坪涂鸦街"], afternoon: ["弹子石老街"], evening: ["火锅 farewell"], walkLevel: "约8千步", transport: "打车", nearbyFood: "弹子石老街" },
      ],
      intense: [
        { label: "Day1", morning: ["李子坝→鹅岭二厂"], afternoon: ["解放碑→山城第三步道→长江索道"], evening: ["洪崖洞→千厮门大桥"], walkLevel: "约2万步", transport: "地铁+步行", nearbyFood: "八一路" },
        { label: "Day2", morning: ["磁器口→歌乐山"], afternoon: ["川美黄桷坪→涂鸦街"], evening: ["弹子石老街→南滨路夜景"], walkLevel: "约2万步", transport: "地铁+打车", nearbyFood: "弹子石" },
        { label: "Day3", morning: ["武隆天坑(一日游)"], afternoon: ["武隆天坑"], evening: ["回城火锅"], walkLevel: "约1.5万步", transport: "大巴/包车", nearbyFood: "回城吃火锅" },
      ],
    },
    packingList: [
      { name: "平底鞋(必须)", category: "clothing", required: true },
      { name: "轻薄外套", category: "clothing", required: true },
      { name: "肠胃药", category: "medicine", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "雨伞", category: "gear", required: true },
    ],
    nearbyFrom: ["成都"],
    nearbyDistance: "高铁1.5小时",
    holidayWarning: "洪崖洞国庆限流排队2小时+",
    holidayAlternative: "弹子石老街看夜景人少得多",
  },
  {
    id: "lijiang",
    name: "丽江",
    province: "云南",
    tagline: "彩云之南，雪山之下",
    gradient: "from-sky-400 via-cyan-200 to-white",
    isNiche: false,
    destTypes: ["ancient_city", "mountain", "ethnic", "nature"],
    durationRange: "5-7d",
    budgetRange: "luxury",
    seasons: ["spring", "autumn"],
    bestTime: "4-5月 / 9-10月",
    duration: "5-6天",
    budget: "人均3000-5000元",
    transportHub: "丽江三义机场/丽江站",
    coreTip: "古城维护费50元，但晚上6点后免费进入",
    funSpots: [
      { name: "玉龙雪山", tagline: "纳西族圣山", ticket: "大索道180元+进山费100元", duration: "1天", bestTime: "上午9点前抢索道票", tips: "提前3天抢大索道票！备好氧气瓶", priority: "must" },
      { name: "束河古镇", tagline: "比大研安静10倍", ticket: "免费", duration: "3-4小时", bestTime: "上午闲逛下午喝茶", tips: "适合发呆写明信片，比大研更有味", priority: "must" },
      { name: "泸沽湖", tagline: "天湖仙境", ticket: "70元", duration: "2天1夜", bestTime: "全年皆宜", tips: "距丽江4小时车程，住一晚看星空", priority: "must" },
      { name: "蓝月谷", tagline: "雪山脚蓝宝石", ticket: "含在索道票内", duration: "1-2小时", bestTime: "下午阳光时水最蓝", tips: "索道下来顺路，别单独跑一趟", priority: "niche" },
      { name: "拉市海骑马", tagline: "茶马古道体验", ticket: "100-200元", bestTime: "上午", duration: "2-3小时", tips: "选正规马场，路边拉客的别去", priority: "nearby" },
    ],
    food: [
      { name: "腊排骨火锅", pricePerPerson: "40-60元", howToEat: "古城外的小店更实在，排骨越煮越香", pitfall: "古城内溢价50%+" },
      { name: "鸡豆凉粉", pricePerPerson: "8-12元", howToEat: "热吃凉吃都行，蘸辣椒面更香", pitfall: "纳西族特色，别跟普通凉粉比" },
      { name: "纳西烤鱼", pricePerPerson: "30-50元", howToEat: "香茅草包裹烤制，风味独特", pitfall: "选整条烤的，切片的不是正宗做法" },
      { name: "水性杨花", pricePerPerson: "15-25元", howToEat: "一种水草蔬菜，口感滑嫩清炒最香", pitfall: "名字有趣但真的好吃，别被吓到" },
      { name: "过桥米线", pricePerPerson: "15-30元", howToEat: "先放荤后放素，等熟再吃", pitfall: "丽江的不如昆明正宗，尝尝就好" },
    ],
    foodAreas: [
      { name: "大研古城五一街", location: "古城区五一街", bestTime: "午餐/晚餐", direction: "避开酒吧街，五一街小馆子更多本地味" },
      { name: "忠义市场", location: "古城区忠义路", bestTime: "早餐/午餐", direction: "本地人菜市场，最真实的丽江味道" },
      { name: "束河老街", location: "束河古镇内", bestTime: "午餐", direction: "比大研便宜，小馆子更地道" },
    ],
    shopping: [
      { name: "古城四方街", category: "old_street", duration: "1-2小时", highlight: "晚上篝火打跳，购物需砍价", forWho: "散步/体验" },
      { name: "忠义市场", category: "night_market", duration: "1小时", highlight: "本地人菜市场，最真实的丽江", forWho: "淘货/体验" },
      { name: "束河老街", category: "old_street", duration: "2小时", highlight: "手工艺品比大研更精致", forWho: "购物/文艺" },
    ],
    pitfalls: [
      { category: "scenic", content: "古城维护费50元，但晚上6点后免费进入" },
      { category: "general", content: "酒吧街的艳遇故事99%是酒托" },
      { category: "scenic", content: "玉龙雪山别信黄牛说能免索道费" },
      { category: "general", content: "别买银器玉器，水太深" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["大研古城漫步"], afternoon: ["五一街觅食"], evening: ["四方街篝火打跳"], walkLevel: "约8千步", transport: "步行", nearbyFood: "五一街小馆" },
        { label: "Day2", morning: ["束河古镇"], afternoon: ["束河喝茶发呆"], evening: ["古城夜景"], walkLevel: "约6千步", transport: "打车/公交", nearbyFood: "束河老街" },
        { label: "Day3", morning: ["玉龙雪山(大索道)"], afternoon: ["蓝月谷"], evening: ["古城休息"], walkLevel: "约1万步", transport: "包车/大巴", nearbyFood: "古城晚餐" },
        { label: "Day4-5", morning: ["泸沽湖出发"], afternoon: ["泸沽湖环湖"], evening: ["泸沽湖星空"], walkLevel: "约5千步", transport: "包车", nearbyFood: "湖边餐厅" },
      ],
      intense: [
        { label: "Day1", morning: ["大研古城→木府→狮子山"], afternoon: ["五一街→忠义市场"], evening: ["四方街篝火+酒吧街(只看看)"], walkLevel: "约1.5万步", transport: "步行", nearbyFood: "忠义市场" },
        { label: "Day2", morning: ["玉龙雪山(大索道登顶)"], afternoon: ["蓝月谷→甘海子"], evening: ["古城晚餐"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "古城外腊排骨" },
        { label: "Day3", morning: ["束河古镇→白沙古镇"], afternoon: ["拉市海骑马"], evening: ["束河晚餐"], walkLevel: "约1.2万步", transport: "打车", nearbyFood: "束河小馆" },
        { label: "Day4-5", morning: ["泸沽湖出发(4小时)"], afternoon: ["环湖+划船+里务比岛"], evening: ["篝火晚会+星空"], walkLevel: "约8千步", transport: "包车", nearbyFood: "湖边摩梭族餐" },
      ],
    },
    packingList: [
      { name: "防晒霜SPF50+", category: "gear", required: true },
      { name: "厚外套(昼夜温差大)", category: "clothing", required: true },
      { name: "氧气瓶(雪山用)", category: "medicine", required: true },
      { name: "帽子墨镜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "背包(石板路行李箱受罪)", category: "gear", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    holidayWarning: "国庆古城人挤人，索道票更难抢",
    holidayAlternative: "束河+白沙古镇，同样纳西风情人少得多",
  },
  {
    id: "xiamen",
    name: "厦门",
    province: "福建",
    tagline: "海上花园，文艺慢城",
    gradient: "from-cyan-300 via-blue-200 to-orange-200",
    isNiche: false,
    destTypes: ["island", "city_walk", "ancient_city"],
    durationRange: "3-4d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn", "winter"],
    bestTime: "3-5月 / 10-12月",
    duration: "3-4天",
    budget: "人均1500-2500元",
    transportHub: "高崎机场/厦门站/厦门北站",
    coreTip: "鼓浪屿船票要提前买，节假日现场买不到",
    funSpots: [
      { name: "鼓浪屿", tagline: "万国建筑博览", ticket: "船票35元往返", duration: "1天", bestTime: "上午第一批船上岛", tips: "迷路是最好的游览方式，别按攻略走", priority: "must" },
      { name: "厦门大学", tagline: "中国最美大学", ticket: "免费(需预约)", duration: "2-3小时", bestTime: "上午人少", tips: "芙蓉隧道涂鸦墙+情人谷", priority: "must" },
      { name: "环岛路骑行", tagline: "海边自行车道", ticket: "租车20-30元", duration: "2-3小时", bestTime: "傍晚5-7点日落", tips: "从白城沙滩骑到黄厝，最美海滨路", priority: "must" },
      { name: "南普陀寺", tagline: "千年古刹", ticket: "免费", duration: "1-2小时", bestTime: "上午清净", tips: "素饼好吃可做伴手礼", priority: "niche" },
      { name: "沙坡尾", tagline: "老渔港变艺术区", ticket: "免费", duration: "1-2小时", bestTime: "下午4-6点", tips: "文创店好逛，避风坞拍照出片", priority: "nearby" },
    ],
    food: [
      { name: "沙茶面", pricePerPerson: "15-25元", howToEat: "汤底是灵魂，加大肠+豆腐+鱿鱼", pitfall: "月华和乌糖最出名但排队，小巷里也好吃" },
      { name: "海蛎煎", pricePerPerson: "20-30元", howToEat: "蘸甜辣酱吃，外酥内嫩", pitfall: "别在景区吃，去八市附近" },
      { name: "花生汤", pricePerPerson: "8-12元", howToEat: "黄则和最出名，早餐来一碗", pitfall: "很甜，不爱甜口慎点" },
      { name: "土笋冻", pricePerPerson: "10-15元", howToEat: "勇气试炼！蘸芥末酱油吃", pitfall: "其实是海土蚯蚓，口感像果冻" },
      { name: "姜母鸭", pricePerPerson: "40-60元", howToEat: "药膳焖鸭，冬天吃暖到心底", pitfall: "冬天吃最好，夏天略腻" },
    ],
    foodAreas: [
      { name: "八市(第八菜市场)", location: "思明区开禾路", bestTime: "早餐/午餐", direction: "最地道的厦门烟火，海鲜+小吃" },
      { name: "中山路", location: "思明区中山路", bestTime: "午餐/晚餐", direction: "百年骑楼商业街，边逛边吃" },
      { name: "沙坡尾", location: "思明区沙坡尾", bestTime: "下午茶/晚餐", direction: "文创+咖啡+小酒馆" },
    ],
    shopping: [
      { name: "中山路", category: "old_street", duration: "2-3小时", highlight: "百年骑楼商业街，建筑比商品值得看", forWho: "散步/拍照" },
      { name: "沙坡尾市集", category: "night_market", duration: "1-2小时", highlight: "周末创意市集，手作和独立设计", forWho: "文艺/淘货" },
      { name: "八市", category: "night_market", duration: "1小时", highlight: "最地道的厦门烟火", forWho: "吃货/体验" },
    ],
    pitfalls: [
      { category: "scenic", content: "鼓浪屿船票要提前买，节假日现场买不到" },
      { category: "scenic", content: "曾厝垵已过度商业化，住可以逛不必久留" },
      { category: "scenic", content: "厦大限流需预约，别忘了提前在公众号抢" },
      { category: "food", content: "海鲜大排挡注意看秤，防缺斤少两" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["鼓浪屿(全天)"], afternoon: ["鼓浪屿漫步"], evening: ["返回中山路晚餐"], walkLevel: "约1.5万步", transport: "轮渡+步行", nearbyFood: "中山路小吃" },
        { label: "Day2", morning: ["南普陀寺"], afternoon: ["厦门大学+芙蓉隧道"], evening: ["沙坡尾"], walkLevel: "约1万步", transport: "步行", nearbyFood: "沙坡尾" },
        { label: "Day3", morning: ["环岛路骑行"], afternoon: ["曾厝垵(路过)"], evening: ["八市觅食"], walkLevel: "约1万步", transport: "自行车+公交", nearbyFood: "八市" },
      ],
      intense: [
        { label: "Day1", morning: ["鼓浪屿(首批船)"], afternoon: ["日光岩→菽庄花园→皓月园"], evening: ["中山路→八市"], walkLevel: "约2万步", transport: "轮渡+步行", nearbyFood: "八市" },
        { label: "Day2", morning: ["南普陀寺→五老峰"], afternoon: ["厦大→芙蓉隧道→环岛路骑行"], evening: ["沙坡尾→曾厝垵"], walkLevel: "约2.2万步", transport: "步行+自行车", nearbyFood: "沙坡尾" },
        { label: "Day3", morning: ["集美学村"], afternoon: ["园博苑→海沧大桥"], evening: ["中山路 farewell"], walkLevel: "约1.5万步", transport: "地铁+步行", nearbyFood: "中山路" },
      ],
    },
    packingList: [
      { name: "防晒霜", category: "gear", required: true },
      { name: "拖鞋(海边)", category: "clothing", required: true },
      { name: "薄外套(海风大)", category: "clothing", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "泳衣", category: "clothing", required: false },
    ],
    nearbyFrom: ["福州", "泉州"],
    nearbyDistance: "高铁1-2小时",
  },
];
