import type { CityGuide } from "./types";

// 新增城市数据
export const newCities: CityGuide[] = [
  {
    id: "nanjing",
    name: "南京",
    province: "江苏",
    tagline: "六朝古都，十朝都会",
    gradient: "from-amber-300 via-orange-200 to-red-200",
    isNiche: false,
    destTypes: ["ancient_city", "food_city"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn"],
    bestTime: "3-5月 / 9-11月",
    duration: "3-4天",
    budget: "人均1200-2500元",
    transportHub: "禄口机场/南京南站",
    coreTip: "中山陵免费但需提前预约，周一闭馆",
    funSpots: [
      { name: "中山陵", tagline: "国父陵寝", ticket: "免费(需预约)", duration: "2-3小时", bestTime: "上午8:30开门即入", tips: "周一闭馆，提前在公众号预约", priority: "must" },
      { name: "夫子庙秦淮河", tagline: "金陵第一名胜", ticket: "免费(游船另付)", duration: "3-4小时", bestTime: "傍晚至夜景", tips: "白天逛景点，晚上看夜景坐游船", priority: "must" },
      { name: "总统府", tagline: "近代史博物馆", ticket: "35元", duration: "2-3小时", bestTime: "上午人少", tips: "1842展厅最震撼，别只看建筑", priority: "must" },
      { name: "明孝陵", tagline: "朱元璋陵墓", ticket: "70元", duration: "2-3小时", bestTime: "秋季神道最美", tips: "石象路神道秋天银杏金黄", priority: "niche" },
      { name: "玄武湖", tagline: "城中湖泊", ticket: "免费", duration: "2-3小时", bestTime: "傍晚散步", tips: "环湖骑行最惬意，城墙根下拍照", priority: "nearby" },
    ],
    food: [
      { name: "盐水鸭", pricePerPerson: "40-60元", howToEat: "皮白肉嫩，冷吃最佳", pitfall: "韩复兴最正宗但排队" },
      { name: "鸭血粉丝汤", pricePerPerson: "15-25元", howToEat: "鸭血鸭肠鸭肝全加，配烧饼", pitfall: "回味鸭血粉丝汤最出名" },
      { name: "小笼包", pricePerPerson: "20-30元", howToEat: "先开窗喝汤，再吃皮和馅", pitfall: "鸡鸣汤包最地道" },
      { name: "桂花糖芋苗", pricePerPerson: "8-12元", howToEat: "甜糯暖胃，秋冬必吃", pitfall: "蓝老大最正宗" },
      { name: "牛肉锅贴", pricePerPerson: "15-20元", howToEat: "底部金黄酥脆，一口爆汁", pitfall: "李记清真馆排队最长" },
    ],
    foodAreas: [
      { name: "老门东", location: "秦淮区老门东", bestTime: "下午+晚餐", direction: "历史街区+小吃集中" },
      { name: "狮子桥美食街", location: "鼓楼区狮子桥", bestTime: "晚餐/夜宵", direction: "本地人爱去，种类丰富" },
      { name: "科巷", location: "秦淮区科巷", bestTime: "早餐/午餐", direction: "菜市场改造，平价美食" },
    ],
    shopping: [
      { name: "德基广场", category: "mall", duration: "2-3小时", highlight: "南京最高端商场，品牌齐全", forWho: "购物" },
      { name: "老门东", category: "old_street", duration: "2-3小时", highlight: "历史街区，文艺小店", forWho: "散步/拍照" },
      { name: "先锋书店", category: "old_street", duration: "1-2小时", highlight: "全球最美书店之一", forWho: "文艺/拍照" },
    ],
    pitfalls: [
      { category: "scenic", content: "中山陵周一闭馆，别跑空" },
      { category: "traffic", content: "夫子庙周末人挤人，工作日去体验好" },
      { category: "food", content: "夫子庙主街小吃贵且不正宗，去老门东" },
      { category: "general", content: "春秋温差大，带件外套" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["中山陵(8:30入园)"], afternoon: ["明孝陵→石象路"], evening: ["夫子庙秦淮河夜景"], walkLevel: "约1.2万步", transport: "地铁+步行", nearbyFood: "老门东晚餐" },
        { label: "Day2", morning: ["总统府"], afternoon: ["玄武湖环湖"], evening: ["狮子桥美食街"], walkLevel: "约1万步", transport: "地铁+步行", nearbyFood: "狮子桥小吃" },
        { label: "Day3", morning: ["先锋书店"], afternoon: ["老门东闲逛"], evening: ["科巷美食"], walkLevel: "约8千步", transport: "地铁+步行", nearbyFood: "科巷小吃" },
      ],
      intense: [
        { label: "Day1", morning: ["中山陵"], afternoon: ["明孝陵→美龄宫"], evening: ["夫子庙→老门东"], walkLevel: "约1.5万步", transport: "地铁+步行", nearbyFood: "老门东" },
        { label: "Day2", morning: ["总统府"], afternoon: ["玄武湖→鸡鸣寺"], evening: ["狮子桥→科巷"], walkLevel: "约1.8万步", transport: "地铁+步行", nearbyFood: "科巷" },
        { label: "Day3", morning: ["侵华日军南京大屠杀遇难同胞纪念馆"], afternoon: ["先锋书店→新街口"], evening: ["德基广场"], walkLevel: "约1.2万步", transport: "地铁", nearbyFood: "新街口" },
        { label: "Day4", morning: ["牛首山"], afternoon: ["牛首山→返程"], evening: ["南京南站"], walkLevel: "约1.5万步", transport: "打车", nearbyFood: "牛首山景区" },
      ],
    },
    packingList: [
      { name: "轻薄外套", category: "clothing", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "雨伞", category: "gear", required: false },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    nearbyFrom: ["上海", "合肥"],
    nearbyDistance: "高铁1-1.5小时",
    holidayWarning: "国庆/五一夫子庙人山人海",
    holidayAlternative: "老门东相对人少",
  },
  {
    id: "wuhan",
    name: "武汉",
    province: "湖北",
    tagline: "九省通衢，江城武汉",
    gradient: "from-blue-300 via-cyan-200 to-teal-200",
    isNiche: false,
    destTypes: ["food_city", "ancient_city"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn"],
    bestTime: "3-5月 / 9-11月",
    duration: "3-4天",
    budget: "人均1000-2000元",
    transportHub: "天河机场/武汉站/汉口站",
    coreTip: "热干面要趁热拌开，凉了会坨",
    funSpots: [
      { name: "黄鹤楼", tagline: "天下江山第一楼", ticket: "70元", duration: "2-3小时", bestTime: "上午人少", tips: "登顶看长江大桥和武昌城区", priority: "must" },
      { name: "东湖绿道", tagline: "城中湖绿道", ticket: "免费", duration: "3-4小时", bestTime: "下午骑行", tips: "磨山段最美，租自行车环湖", priority: "must" },
      { name: "武汉大学", tagline: "最美大学", ticket: "免费(需预约)", duration: "2-3小时", bestTime: "3月樱花季", tips: "非樱花季也美，民国建筑", priority: "must" },
      { name: "户部巷", tagline: "汉味小吃街", ticket: "免费", duration: "1-2小时", bestTime: "早餐时段", tips: "热干面豆皮面窝一站吃齐", priority: "niche" },
      { name: "江汉路步行街", tagline: "百年商业街", ticket: "免费", duration: "2-3小时", bestTime: "傍晚散步", tips: "近代建筑群，夜景漂亮", priority: "nearby" },
    ],
    food: [
      { name: "热干面", pricePerPerson: "8-12元", howToEat: "趁热快速拌开，加酸豆角", pitfall: "蔡林记最出名但本地人爱赵师傅" },
      { name: "三鲜豆皮", pricePerPerson: "10-15元", howToEat: "糯米+肉丁+香菇，外脆内软", pitfall: "老通城最正宗" },
      { name: "武昌鱼", pricePerPerson: "50-80元", howToEat: "清蒸最鲜，红烧入味", pitfall: "大中华酒楼最正宗" },
      { name: "鸭脖", pricePerPerson: "20-40元", howToEat: "麻辣过瘾，配啤酒绝了", pitfall: "周黑鸭最出名但精武路更地道" },
      { name: "面窝", pricePerPerson: "3-5元", howToEat: "早餐配热干面，外酥里嫩", pitfall: "户部巷最集中" },
    ],
    foodAreas: [
      { name: "户部巷", location: "武昌区户部巷", bestTime: "早餐", direction: "汉味小吃集中" },
      { name: "吉庆街", location: "江岸区吉庆街", bestTime: "晚餐/夜宵", direction: "大排档+宵夜" },
      { name: "万松园", location: "江汉区万松园", bestTime: "晚餐", direction: "本地人爱去，种类多" },
    ],
    shopping: [
      { name: "楚河汉街", category: "mall", duration: "3-4小时", highlight: "世界级城市商业步行街", forWho: "购物/散步" },
      { name: "江汉路步行街", category: "old_street", duration: "2-3小时", highlight: "百年商业街，近代建筑", forWho: "散步/拍照" },
      { name: "光谷步行街", category: "mall", duration: "2-3小时", highlight: "欧式建筑，年轻人聚集", forWho: "购物/拍照" },
    ],
    pitfalls: [
      { category: "general", content: "夏天酷热，冬天湿冷，春秋最佳" },
      { category: "traffic", content: "过江交通拥堵，地铁更高效" },
      { category: "food", content: "户部巷主街贵，去支巷更地道" },
      { category: "general", content: "带肠胃药，小吃太多容易吃撑" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["黄鹤楼"], afternoon: ["户部巷→长江大桥"], evening: ["江汉路步行街"], walkLevel: "约1.2万步", transport: "地铁+步行", nearbyFood: "户部巷" },
        { label: "Day2", morning: ["武汉大学"], afternoon: ["东湖绿道骑行"], evening: ["楚河汉街"], walkLevel: "约1万步", transport: "地铁+骑行", nearbyFood: "楚河汉街" },
        { label: "Day3", morning: ["湖北省博物馆"], afternoon: ["光谷步行街"], evening: ["万松园美食"], walkLevel: "约8千步", transport: "地铁", nearbyFood: "万松园" },
      ],
      intense: [
        { label: "Day1", morning: ["黄鹤楼"], afternoon: ["户部巷→长江大桥→江滩"], evening: ["江汉路→吉庆街"], walkLevel: "约1.8万步", transport: "地铁+步行", nearbyFood: "吉庆街" },
        { label: "Day2", morning: ["武汉大学"], afternoon: ["东湖磨山→绿道骑行"], evening: ["楚河汉街"], walkLevel: "约1.5万步", transport: "地铁+骑行", nearbyFood: "楚河汉街" },
        { label: "Day3", morning: ["湖北省博物馆"], afternoon: ["昙华林→户部巷"], evening: ["万松园"], walkLevel: "约1.2万步", transport: "地铁+步行", nearbyFood: "万松园" },
        { label: "Day4", morning: ["归元寺"], afternoon: ["汉阳造→晴川阁"], evening: ["长江轮渡→江滩"], walkLevel: "约1.5万步", transport: "地铁+轮渡", nearbyFood: "江滩" },
      ],
    },
    packingList: [
      { name: "轻薄外套", category: "clothing", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "雨伞", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    nearbyFrom: ["长沙", "郑州"],
    nearbyDistance: "高铁1.5-2小时",
    holidayWarning: "国庆/五一黄鹤楼排队1小时+",
    holidayAlternative: "晴川阁人少景美",
  },
  {
    id: "qingdao",
    name: "青岛",
    province: "山东",
    tagline: "红瓦绿树，碧海蓝天",
    gradient: "from-sky-400 via-blue-300 to-cyan-200",
    isNiche: false,
    destTypes: ["island", "food_city"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["summer", "autumn"],
    bestTime: "5-10月",
    duration: "3-4天",
    budget: "人均1500-2800元",
    transportHub: "流亭机场/胶东机场/青岛站",
    coreTip: "啤酒要喝原浆，海鲜要问价格",
    funSpots: [
      { name: "栈桥", tagline: "青岛地标", ticket: "免费", duration: "1-2小时", bestTime: "清晨或傍晚", tips: "回澜阁门票4元，可登顶看海", priority: "must" },
      { name: "八大关", tagline: "万国建筑博览", ticket: "免费", duration: "2-3小时", bestTime: "上午散步", tips: "花石楼公主楼必打卡", priority: "must" },
      { name: "崂山", tagline: "海上名山第一", ticket: "150元(含景区大巴)", duration: "1天", bestTime: "上午出发", tips: "南线最经典，北九水秋天最美", priority: "must" },
      { name: "金沙滩", tagline: "亚洲第一滩", ticket: "免费", duration: "3-4小时", bestTime: "下午游泳", tips: "沙质细腻，比市区海滩好", priority: "niche" },
      { name: "信号山公园", tagline: "老城全景", ticket: "10元", duration: "1-2小时", bestTime: "傍晚看日落", tips: "旋转观景台看红瓦绿树碧海蓝天", priority: "nearby" },
    ],
    food: [
      { name: "海鲜", pricePerPerson: "100-200元", howToEat: "辣炒蛤蜊+鲅鱼饺子+烤鱿鱼", pitfall: "先问价再点，景区海鲜贵" },
      { name: "青岛啤酒", pricePerPerson: "10-20元", howToEat: "原浆最鲜，纯生次之", pitfall: "啤酒街氛围好但贵" },
      { name: "鲅鱼饺子", pricePerPerson: "30-50元", howToEat: "皮薄馅大，蘸醋吃", pitfall: "船歌鱼水饺最出名" },
      { name: "排骨米饭", pricePerPerson: "20-30元", howToEat: "排骨酥烂，米饭吸汁", pitfall: "万和春最正宗" },
      { name: "烤鱿鱼", pricePerPerson: "10-15元", howToEat: "现烤现吃，配啤酒", pitfall: "栈桥附近最集中" },
    ],
    foodAreas: [
      { name: "劈柴院", location: "市南区劈柴院", bestTime: "晚餐/夜宵", direction: "老字号集中，但游客多" },
      { name: "台东步行街", location: "市北区台东", bestTime: "晚餐", direction: "本地人爱去，种类丰富" },
      { name: "闽江路美食街", location: "市南区闽江路", bestTime: "晚餐", direction: "海鲜大排档集中" },
    ],
    shopping: [
      { name: "万象城", category: "mall", duration: "2-3小时", highlight: "青岛最高端商场", forWho: "购物" },
      { name: "台东步行街", category: "old_street", duration: "2-3小时", highlight: "百年商业街，热闹", forWho: "散步/购物" },
      { name: "大学路", category: "old_street", duration: "1-2小时", highlight: "文艺小巷，咖啡馆", forWho: "文艺/拍照" },
    ],
    pitfalls: [
      { category: "food", content: "景区海鲜贵且可能不新鲜，去本地人餐厅" },
      { category: "general", content: "夏天潮湿，冬天风大，春秋最佳" },
      { category: "scenic", content: "栈桥周末人挤人，工作日去" },
      { category: "general", content: "带防晒霜和外套，海边风大" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["栈桥"], afternoon: ["八大关"], evening: ["信号山看日落"], walkLevel: "约1万步", transport: "地铁+步行", nearbyFood: "闽江路" },
        { label: "Day2", morning: ["崂山(南线)"], afternoon: ["崂山→返程"], evening: ["台东步行街"], walkLevel: "约1.5万步", transport: "打车", nearbyFood: "台东" },
        { label: "Day3", morning: ["金沙滩"], afternoon: ["金沙滩游泳"], evening: ["劈柴院"], walkLevel: "约8千步", transport: "打车", nearbyFood: "劈柴院" },
      ],
      intense: [
        { label: "Day1", morning: ["栈桥"], afternoon: ["八大关→信号山"], evening: ["闽江路"], walkLevel: "约1.5万步", transport: "地铁+步行", nearbyFood: "闽江路" },
        { label: "Day2", morning: ["崂山(南线)"], afternoon: ["崂山→太清宫"], evening: ["台东"], walkLevel: "约2万步", transport: "打车", nearbyFood: "台东" },
        { label: "Day3", morning: ["金沙滩"], afternoon: ["金沙滩→啤酒城"], evening: ["劈柴院"], walkLevel: "约1.2万步", transport: "打车", nearbyFood: "劈柴院" },
        { label: "Day4", morning: ["小鱼山"], afternoon: ["大学路→老舍故居"], evening: ["万象城"], walkLevel: "约1万步", transport: "地铁+步行", nearbyFood: "万象城" },
      ],
    },
    packingList: [
      { name: "泳衣", category: "clothing", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "轻薄外套", category: "clothing", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    nearbyFrom: ["济南", "烟台"],
    nearbyDistance: "高铁1-1.5小时",
    holidayWarning: "国庆/五一金沙滩人满为患",
    holidayAlternative: "石老人海滩人少",
  },
  {
    id: "sanya",
    name: "三亚",
    province: "海南",
    tagline: "东方夏威夷，热带天堂",
    gradient: "from-cyan-300 via-teal-200 to-emerald-200",
    isNiche: false,
    destTypes: ["island", "hot_spring"],
    durationRange: "4-7d",
    budgetRange: "luxury",
    seasons: ["winter", "spring"],
    bestTime: "10月-次年3月",
    duration: "4-5天",
    budget: "人均3000-6000元",
    transportHub: "凤凰机场",
    coreTip: "防晒霜SPF50+必备，紫外线极强",
    funSpots: [
      { name: "亚龙湾", tagline: "天下第一湾", ticket: "免费", duration: "3-4小时", bestTime: "下午游泳", tips: "沙质最细，水最清，酒店私滩人少", priority: "must" },
      { name: "蜈支洲岛", tagline: "中国马尔代夫", ticket: "144元(含船票)", duration: "1天", bestTime: "上午出发", tips: "潜水最佳地点，提前网上订票", priority: "must" },
      { name: "南山寺", tagline: "海上观音", ticket: "129元", duration: "3-4小时", bestTime: "上午", tips: "108米海上观音震撼，别错过", priority: "must" },
      { name: "呀诺达雨林", tagline: "热带雨林", ticket: "150元(含电瓶车)", duration: "半天", bestTime: "上午", tips: "踏瀑戏水最刺激，带换洗衣物", priority: "niche" },
      { name: "鹿回头", tagline: "三亚夜景", ticket: "45元", duration: "2小时", bestTime: "傍晚看日落", tips: "俯瞰三亚湾夜景最佳地点", priority: "nearby" },
    ],
    food: [
      { name: "海鲜", pricePerPerson: "150-300元", howToEat: "和乐蟹+基围虾+芒果螺", pitfall: "第一市场买海鲜去加工" },
      { name: "椰子鸡", pricePerPerson: "80-120元", howToEat: "椰子水做汤底，清甜鲜美", pitfall: "嗲嗲的椰子鸡最出名" },
      { name: "清补凉", pricePerPerson: "10-15元", howToEat: "椰奶+红豆+薏米+水果，冰爽", pitfall: "街头小摊最正宗" },
      { name: "抱罗粉", pricePerPerson: "15-20元", howToEat: "海南四大名粉之一，汤鲜粉滑", pitfall: "早餐吃最地道" },
      { name: "芒果肠粉", pricePerPerson: "15-25元", howToEat: "芒果+肠粉，甜而不腻", pitfall: "网红甜品，排队久" },
    ],
    foodAreas: [
      { name: "第一市场", location: "天涯区第一市场", bestTime: "晚餐", direction: "买海鲜去加工，最实惠" },
      { name: "解放路步行街", location: "天涯区解放路", bestTime: "晚餐/夜宵", direction: "小吃集中" },
      { name: "亚龙湾奥特莱斯", location: "吉阳区亚龙湾", bestTime: "晚餐", direction: "高端餐厅集中" },
    ],
    shopping: [
      { name: "海棠湾免税店", category: "mall", duration: "3-4小时", highlight: "全球最大单体免税店", forWho: "购物" },
      { name: "亚龙湾奥特莱斯", category: "mall", duration: "2-3小时", highlight: "品牌折扣", forWho: "购物" },
      { name: "解放路步行街", category: "old_street", duration: "1-2小时", highlight: "小吃+特产", forWho: "散步/购物" },
    ],
    pitfalls: [
      { category: "scenic", content: "天涯海角就是几块石头，拍照打卡即可" },
      { category: "food", content: "景区海鲜贵，去第一市场买海鲜加工" },
      { category: "general", content: "防晒霜必备，SPF50+，2小时补涂" },
      { category: "traffic", content: "打车难，租车或包车更方便" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["亚龙湾"], afternoon: ["亚龙湾游泳"], evening: ["亚龙湾奥特莱斯"], walkLevel: "约6千步", transport: "打车", nearbyFood: "亚龙湾" },
        { label: "Day2", morning: ["蜈支洲岛"], afternoon: ["蜈支洲岛潜水"], evening: ["第一市场"], walkLevel: "约1万步", transport: "打车+船", nearbyFood: "第一市场" },
        { label: "Day3", morning: ["南山寺"], afternoon: ["鹿回头"], evening: ["解放路"], walkLevel: "约1.2万步", transport: "打车", nearbyFood: "解放路" },
      ],
      intense: [
        { label: "Day1", morning: ["亚龙湾"], afternoon: ["亚龙湾→鹿回头"], evening: ["解放路"], walkLevel: "约1.2万步", transport: "打车", nearbyFood: "解放路" },
        { label: "Day2", morning: ["蜈支洲岛"], afternoon: ["蜈支洲岛潜水"], evening: ["第一市场"], walkLevel: "约1.5万步", transport: "打车+船", nearbyFood: "第一市场" },
        { label: "Day3", morning: ["南山寺"], afternoon: ["大小洞天"], evening: ["三亚湾"], walkLevel: "约1.8万步", transport: "打车", nearbyFood: "三亚湾" },
        { label: "Day4", morning: ["呀诺达雨林"], afternoon: ["呀诺达→海棠湾"], evening: ["海棠湾免税店"], walkLevel: "约1.5万步", transport: "打车", nearbyFood: "海棠湾" },
      ],
    },
    packingList: [
      { name: "泳衣", category: "clothing", required: true },
      { name: "防晒霜SPF50+", category: "gear", required: true },
      { name: "墨镜", category: "gear", required: true },
      { name: "沙滩鞋", category: "clothing", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    nearbyFrom: ["海口"],
    nearbyDistance: "高铁1.5小时",
    holidayWarning: "国庆/春节房价翻3倍，提前订",
    holidayAlternative: "万宁陵水人少",
  },
  {
    id: "guangzhou",
    name: "广州",
    province: "广东",
    tagline: "食在广州，花城广州",
    gradient: "from-pink-300 via-rose-200 to-amber-200",
    isNiche: false,
    destTypes: ["food_city", "ancient_city"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn", "winter"],
    bestTime: "10月-次年3月",
    duration: "3-4天",
    budget: "人均1200-2500元",
    transportHub: "白云机场/广州南站",
    coreTip: "早茶要趁热吃，凉茶苦但有效",
    funSpots: [
      { name: "广州塔", tagline: "小蛮腰", ticket: "150元", duration: "2-3小时", bestTime: "傍晚看夜景", tips: "摩天轮和跳楼机刺激，恐高慎入", priority: "must" },
      { name: "沙面岛", tagline: "欧式建筑群", ticket: "免费", duration: "2-3小时", bestTime: "上午散步", tips: "欧式建筑+古树，拍照圣地", priority: "must" },
      { name: "陈家祠", tagline: "岭南建筑明珠", ticket: "10元", duration: "1-2小时", bestTime: "上午", tips: "木雕砖雕石雕陶雕，工艺精湛", priority: "must" },
      { name: "白云山", tagline: "广州后花园", ticket: "5元", duration: "半天", bestTime: "上午", tips: "云台花园最美观景台", priority: "niche" },
      { name: "北京路步行街", tagline: "千年商道", ticket: "免费", duration: "2-3小时", bestTime: "傍晚", tips: "地下千年古道遗址必看", priority: "nearby" },
    ],
    food: [
      { name: "早茶", pricePerPerson: "60-100元", howToEat: "虾饺凤爪叉烧包，一盅两件", pitfall: "点都德广州酒家最正宗" },
      { name: "肠粉", pricePerPerson: "10-15元", howToEat: "布拉肠粉最滑，蘸酱油", pitfall: "银记肠粉最出名" },
      { name: "白切鸡", pricePerPerson: "50-80元", howToEat: "皮爽肉滑，蘸姜葱酱", pitfall: "清平鸡最正宗" },
      { name: "云吞面", pricePerPerson: "15-20元", howToEat: "竹升面爽滑，云吞鲜美", pitfall: "宝华面店最地道" },
      { name: "双皮奶", pricePerPerson: "10-15元", howToEat: "顺德双皮奶最正宗，滑嫩", pitfall: "南信牛奶甜品专家" },
    ],
    foodAreas: [
      { name: "上下九步行街", location: "荔湾区上下九", bestTime: "晚餐/夜宵", direction: "老字号集中" },
      { name: "北京路", location: "越秀区北京路", bestTime: "晚餐", direction: "小吃+购物" },
      { name: "体育西路", location: "天河区体育西路", bestTime: "晚餐", direction: "现代餐厅集中" },
    ],
    shopping: [
      { name: "天河城", category: "mall", duration: "2-3小时", highlight: "广州最热闹商场", forWho: "购物" },
      { name: "北京路步行街", category: "old_street", duration: "2-3小时", highlight: "千年商道，购物+小吃", forWho: "购物/散步" },
      { name: "上下九步行街", category: "old_street", duration: "2-3小时", highlight: "骑楼建筑，老字号", forWho: "购物/拍照" },
    ],
    pitfalls: [
      { category: "general", content: "夏天闷热潮湿，春秋最佳" },
      { category: "food", content: "景区周边早茶贵，去老城区更地道" },
      { category: "traffic", content: "地铁高峰期拥挤，避开高峰" },
      { category: "general", content: "带伞，随时可能下雨" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["陈家祠"], afternoon: ["沙面岛"], evening: ["上下九"], walkLevel: "约1万步", transport: "地铁+步行", nearbyFood: "上下九" },
        { label: "Day2", morning: ["白云山"], afternoon: ["广州塔"], evening: ["珠江夜游"], walkLevel: "约1.5万步", transport: "地铁+打车", nearbyFood: "珠江边" },
        { label: "Day3", morning: ["北京路"], afternoon: ["天河城"], evening: ["体育西路"], walkLevel: "约1.2万步", transport: "地铁", nearbyFood: "体育西路" },
      ],
      intense: [
        { label: "Day1", morning: ["陈家祠"], afternoon: ["沙面岛→石室圣心大教堂"], evening: ["上下九"], walkLevel: "约1.5万步", transport: "地铁+步行", nearbyFood: "上下九" },
        { label: "Day2", morning: ["白云山"], afternoon: ["广州塔"], evening: ["珠江夜游"], walkLevel: "约2万步", transport: "地铁+打车", nearbyFood: "珠江边" },
        { label: "Day3", morning: ["北京路"], afternoon: ["越秀公园→五羊雕像"], evening: ["北京路"], walkLevel: "约1.5万步", transport: "地铁+步行", nearbyFood: "北京路" },
        { label: "Day4", morning: ["长隆野生动物世界"], afternoon: ["长隆"], evening: ["天河城"], walkLevel: "约2万步", transport: "地铁", nearbyFood: "天河城" },
      ],
    },
    packingList: [
      { name: "轻薄透气衣物", category: "clothing", required: true },
      { name: "雨伞", category: "gear", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    nearbyFrom: ["深圳", "珠海", "佛山"],
    nearbyDistance: "高铁30分钟-1小时",
    holidayWarning: "国庆/春节长隆排队2小时+",
    holidayAlternative: "白云山沙面人少",
  },
  {
    id: "shenzhen",
    name: "深圳",
    province: "广东",
    tagline: "创新之都，青春之城",
    gradient: "from-blue-400 via-indigo-300 to-purple-200",
    isNiche: false,
    destTypes: ["ancient_city", "food_city"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn", "winter"],
    bestTime: "10月-次年3月",
    duration: "3-4天",
    budget: "人均1500-3000元",
    transportHub: "宝安机场/深圳北站",
    coreTip: "地铁四通八达，打车不如地铁快",
    funSpots: [
      { name: "世界之窗", tagline: "世界微缩景观", ticket: "220元", duration: "3-4小时", bestTime: "全天", tips: "晚上有灯光秀，更震撼", priority: "must" },
      { name: "东部华侨城", tagline: "主题公园", ticket: "180元", duration: "1天", bestTime: "全天", tips: "大峡谷+茶溪谷，选一个即可", priority: "must" },
      { name: "大梅沙海滨公园", tagline: "深圳海滩", ticket: "免费(需预约)", duration: "3-4小时", bestTime: "下午", tips: "周末人多，工作日去", priority: "must" },
      { name: "华侨城创意文化园", tagline: "文艺园区", ticket: "免费", duration: "2-3小时", bestTime: "下午", tips: "OCT创意园拍照圣地", priority: "niche" },
      { name: "深圳湾公园", tagline: "海滨栈道", ticket: "免费", duration: "2-3小时", bestTime: "傍晚", tips: "看日落+对望香港", priority: "nearby" },
    ],
    food: [
      { name: "椰子鸡", pricePerPerson: "100-150元", howToEat: "椰子水做汤底，清甜", pitfall: "润园四季最出名" },
      { name: "潮汕牛肉火锅", pricePerPerson: "120-180元", howToEat: "现切牛肉，涮8秒", pitfall: "八合里海记最正宗" },
      { name: "肠粉", pricePerPerson: "10-15元", howToEat: "布拉肠粉最滑", pitfall: "银记肠粉" },
      { name: "烧鹅", pricePerPerson: "50-80元", howToEat: "皮脆肉嫩，蘸酸梅酱", pitfall: "大同酒家最正宗" },
      { name: "糖水", pricePerPerson: "15-25元", howToEat: "双皮奶姜撞奶，甜而不腻", pitfall: "许留山满记" },
    ],
    foodAreas: [
      { name: "东门老街", location: "罗湖区东门", bestTime: "晚餐/夜宵", direction: "小吃集中" },
      { name: "华强北", location: "福田区华强北", bestTime: "晚餐", direction: "美食街" },
      { name: "海岸城", location: "南山区海岸城", bestTime: "晚餐", direction: "现代餐厅" },
    ],
    shopping: [
      { name: "万象城", category: "mall", duration: "3-4小时", highlight: "深圳最高端商场", forWho: "购物" },
      { name: "东门老街", category: "old_street", duration: "2-3小时", highlight: "深圳最老商业街", forWho: "购物/小吃" },
      { name: "海岸城", category: "mall", duration: "2-3小时", highlight: "南山最热闹商场", forWho: "购物" },
    ],
    pitfalls: [
      { category: "general", content: "夏天闷热，台风季注意天气" },
      { category: "traffic", content: "高峰期堵车严重，地铁更高效" },
      { category: "scenic", content: "世界之窗东部华侨城门票贵，性价比一般" },
      { category: "general", content: "消费水平高，做好预算" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["世界之窗"], afternoon: ["世界之窗"], evening: ["深圳湾公园"], walkLevel: "约1.5万步", transport: "地铁", nearbyFood: "世界之窗" },
        { label: "Day2", morning: ["东部华侨城"], afternoon: ["东部华侨城"], evening: ["大梅沙"], walkLevel: "约2万步", transport: "打车", nearbyFood: "大梅沙" },
        { label: "Day3", morning: ["华侨城创意园"], afternoon: ["深圳博物馆"], evening: ["东门老街"], walkLevel: "约1万步", transport: "地铁", nearbyFood: "东门" },
      ],
      intense: [
        { label: "Day1", morning: ["世界之窗"], afternoon: ["锦绣中华"], evening: ["深圳湾公园"], walkLevel: "约2万步", transport: "地铁", nearbyFood: "世界之窗" },
        { label: "Day2", morning: ["东部华侨城"], afternoon: ["大梅沙"], evening: ["盐田海鲜街"], walkLevel: "约2.5万步", transport: "打车", nearbyFood: "盐田" },
        { label: "Day3", morning: ["华侨城创意园"], afternoon: ["深圳博物馆"], evening: ["东门老街"], walkLevel: "约1.5万步", transport: "地铁", nearbyFood: "东门" },
        { label: "Day4", morning: ["仙湖植物园"], afternoon: ["弘法寺"], evening: ["华强北"], walkLevel: "约2万步", transport: "地铁+打车", nearbyFood: "华强北" },
      ],
    },
    packingList: [
      { name: "轻薄透气衣物", category: "clothing", required: true },
      { name: "雨伞", category: "gear", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    nearbyFrom: ["广州", "珠海", "惠州"],
    nearbyDistance: "高铁30分钟-1小时",
    holidayWarning: "国庆/春节东部华侨城排队2小时+",
    holidayAlternative: "深圳湾公园人少",
  },
  {
    id: "lhasa",
    name: "拉萨",
    province: "西藏",
    tagline: "日光城，雪域圣地",
    gradient: "from-sky-400 via-blue-300 to-indigo-200",
    isNiche: false,
    destTypes: ["hiking", "ethnic"],
    durationRange: "8d+",
    budgetRange: "luxury",
    seasons: ["summer", "autumn"],
    bestTime: "5-10月",
    duration: "5-7天",
    budget: "人均4000-8000元",
    transportHub: "贡嘎机场/拉萨站",
    coreTip: "提前3天吃红景天，高反不是开玩笑",
    funSpots: [
      { name: "布达拉宫", tagline: "世界屋脊的宫殿", ticket: "200元(旺季)", duration: "3-4小时", bestTime: "上午", tips: "提前1天预约，限流5000人", priority: "must" },
      { name: "大昭寺", tagline: "藏传佛教圣地", ticket: "85元", duration: "2-3小时", bestTime: "上午", tips: "释迦牟尼12岁等身像，信徒朝圣地", priority: "must" },
      { name: "八廓街", tagline: "转经道", ticket: "免费", duration: "2-3小时", bestTime: "下午", tips: "顺时针转经，别逆走", priority: "must" },
      { name: "纳木错", tagline: "天湖", ticket: "120元", duration: "1天", bestTime: "6-9月", tips: "海拔4718米，高反者慎入", priority: "niche" },
      { name: "哲蚌寺", tagline: "最大寺庙", ticket: "60元", duration: "2-3小时", bestTime: "上午", tips: "雪顿节晒佛最壮观", priority: "nearby" },
    ],
    food: [
      { name: "酥油茶", pricePerPerson: "10-15元", howToEat: "咸味，配糌粑", pitfall: "初喝不惯，但抗高反" },
      { name: "糌粑", pricePerPerson: "10-15元", howToEat: "青稞炒面，捏成团吃", pitfall: "藏民主食，体验即可" },
      { name: "牦牛肉", pricePerPerson: "60-100元", howToEat: "风干或炖煮，高蛋白", pitfall: "风干牦牛肉最地道" },
      { name: "藏面", pricePerPerson: "15-20元", howToEat: "牦牛骨汤底，粗面条", pitfall: "光明港琼甜茶馆最出名" },
      { name: "甜茶", pricePerPerson: "5-10元", howToEat: "奶茶味，配藏饼", pitfall: "光明港琼甜茶馆" },
    ],
    foodAreas: [
      { name: "八廓街", location: "城关区八廓街", bestTime: "下午", direction: "藏餐+小吃" },
      { name: "德吉南路", location: "城关区德吉南路", bestTime: "晚餐", direction: "藏餐馆集中" },
      { name: "天海夜市", location: "城关区天海夜市", bestTime: "夜宵", direction: "烧烤+小吃" },
    ],
    shopping: [
      { name: "八廓街", category: "old_street", duration: "2-3小时", highlight: "转经道+藏饰手工艺", forWho: "购物/拍照" },
      { name: "宇拓路", category: "mall", duration: "1-2小时", highlight: "拉萨最现代商业街", forWho: "购物" },
    ],
    pitfalls: [
      { category: "general", content: "高反严重，提前吃红景天，别剧烈运动" },
      { category: "scenic", content: "布达拉宫旺季门票难抢，提前1天预约" },
      { category: "general", content: "寺庙内别拍照，顺时针转经" },
      { category: "general", content: "带防晒霜+墨镜，紫外线极强" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["布达拉宫"], afternoon: ["大昭寺"], evening: ["八廓街"], walkLevel: "约8千步", transport: "步行", nearbyFood: "八廓街" },
        { label: "Day2", morning: ["哲蚌寺"], afternoon: ["色拉寺"], evening: ["德吉南路"], walkLevel: "约1万步", transport: "打车", nearbyFood: "德吉南路" },
        { label: "Day3", morning: ["纳木错"], afternoon: ["纳木错→返程"], evening: ["天海夜市"], walkLevel: "约1.2万步", transport: "包车", nearbyFood: "天海夜市" },
      ],
      intense: [
        { label: "Day1", morning: ["布达拉宫"], afternoon: ["大昭寺→八廓街"], evening: ["八廓街转经"], walkLevel: "约1.2万步", transport: "步行", nearbyFood: "八廓街" },
        { label: "Day2", morning: ["哲蚌寺"], afternoon: ["色拉寺辩经"], evening: ["德吉南路"], walkLevel: "约1.5万步", transport: "打车", nearbyFood: "德吉南路" },
        { label: "Day3", morning: ["纳木错"], afternoon: ["纳木错日落"], evening: ["纳木错→拉萨"], walkLevel: "约1万步", transport: "包车", nearbyFood: "纳木错" },
        { label: "Day4", morning: ["罗布林卡"], afternoon: ["西藏博物馆"], evening: ["天海夜市"], walkLevel: "约1.2万步", transport: "打车", nearbyFood: "天海夜市" },
        { label: "Day5", morning: ["羊卓雍错"], afternoon: ["羊卓雍错→返程"], evening: ["八廓街"], walkLevel: "约1万步", transport: "包车", nearbyFood: "八廓街" },
      ],
    },
    packingList: [
      { name: "红景天", category: "medicine", required: true },
      { name: "厚外套", category: "clothing", required: true },
      { name: "防晒霜SPF50+", category: "gear", required: true },
      { name: "墨镜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    nearbyFrom: ["成都"],
    nearbyDistance: "飞机2小时",
    holidayWarning: "国庆/五一布达拉宫门票秒光",
    holidayAlternative: "哲蚌寺色拉寺人少",
  },
  {
    id: "kunming",
    name: "昆明",
    province: "云南",
    tagline: "春城花都，四季如春",
    gradient: "from-pink-300 via-rose-200 to-amber-200",
    isNiche: false,
    destTypes: ["nature", "ethnic"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["spring", "summer", "autumn", "winter"],
    bestTime: "四季皆宜",
    duration: "3-4天",
    budget: "人均1200-2500元",
    transportHub: "长水机场/昆明站",
    coreTip: "紫外线强，防晒必备",
    funSpots: [
      { name: "滇池", tagline: "高原明珠", ticket: "免费", duration: "2-3小时", bestTime: "下午", tips: "海埂大坝喂海鸥，11-3月最佳", priority: "must" },
      { name: "石林", tagline: "天下第一奇观", ticket: "130元", duration: "半天", bestTime: "上午", tips: "阿诗玛化身石必看", priority: "must" },
      { name: "翠湖公园", tagline: "城中翡翠", ticket: "免费", duration: "2小时", bestTime: "上午", tips: "冬天红嘴鸥成群", priority: "must" },
      { name: "云南民族村", tagline: "民族文化", ticket: "90元", duration: "3-4小时", bestTime: "全天", tips: "25个少数民族村寨，表演精彩", priority: "niche" },
      { name: "金马碧鸡坊", tagline: "昆明地标", ticket: "免费", duration: "1小时", bestTime: "傍晚", tips: "夜景漂亮，拍照打卡", priority: "nearby" },
    ],
    food: [
      { name: "过桥米线", pricePerPerson: "30-60元", howToEat: "先放生肉再放蔬菜，最后放米线", pitfall: "桥香园最正宗" },
      { name: "汽锅鸡", pricePerPerson: "60-100元", howToEat: "蒸汽凝结成汤，原汁原味", pitfall: "福照楼最出名" },
      { name: "鲜花饼", pricePerPerson: "10-20元", howToEat: "玫瑰馅最经典，现烤最香", pitfall: "嘉华饼屋" },
      { name: "官渡粑粑", pricePerPerson: "5-10元", howToEat: "胡麻馅最香，现烤", pitfall: "官渡古镇最正宗" },
      { name: "豆花米线", pricePerPerson: "10-15元", howToEat: "凉米线+豆花+酱油，清爽", pitfall: "建新园最出名" },
    ],
    foodAreas: [
      { name: "南屏步行街", location: "五华区南屏街", bestTime: "晚餐", direction: "小吃+餐厅" },
      { name: "文化巷", location: "五华区文化巷", bestTime: "晚餐", direction: "本地人爱去" },
      { name: "官渡古镇", location: "官渡区官渡古镇", bestTime: "下午", direction: "古镇+小吃" },
    ],
    shopping: [
      { name: "南屏步行街", category: "old_street", duration: "2-3小时", highlight: "昆明最热闹商业街", forWho: "购物/散步" },
      { name: "顺城购物中心", category: "mall", duration: "2-3小时", highlight: "市中心商场", forWho: "购物" },
      { name: "官渡古镇", category: "old_street", duration: "2-3小时", highlight: "古镇+小吃+手工艺", forWho: "散步/购物" },
    ],
    pitfalls: [
      { category: "general", content: "紫外线强，防晒必备" },
      { category: "scenic", content: "石林离市区远，预留半天" },
      { category: "food", content: "过桥米线价格差异大，别被宰" },
      { category: "general", content: "早晚温差大，带件外套" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["翠湖公园"], afternoon: ["云南大学"], evening: ["南屏步行街"], walkLevel: "约1万步", transport: "地铁+步行", nearbyFood: "文化巷" },
        { label: "Day2", morning: ["石林"], afternoon: ["石林→返程"], evening: ["金马碧鸡坊"], walkLevel: "约1.5万步", transport: "大巴", nearbyFood: "金马碧鸡坊" },
        { label: "Day3", morning: ["滇池"], afternoon: ["云南民族村"], evening: ["官渡古镇"], walkLevel: "约1.2万步", transport: "打车", nearbyFood: "官渡古镇" },
      ],
      intense: [
        { label: "Day1", morning: ["翠湖公园"], afternoon: ["云南大学→云南师范大学"], evening: ["文化巷"], walkLevel: "约1.2万步", transport: "步行", nearbyFood: "文化巷" },
        { label: "Day2", morning: ["石林"], afternoon: ["石林→九乡"], evening: ["南屏步行街"], walkLevel: "约2万步", transport: "大巴", nearbyFood: "南屏街" },
        { label: "Day3", morning: ["滇池"], afternoon: ["云南民族村"], evening: ["金马碧鸡坊"], walkLevel: "约1.5万步", transport: "打车", nearbyFood: "金马碧鸡坊" },
        { label: "Day4", morning: ["西山"], afternoon: ["西山龙门"], evening: ["官渡古镇"], walkLevel: "约2万步", transport: "打车", nearbyFood: "官渡古镇" },
      ],
    },
    packingList: [
      { name: "防晒霜", category: "gear", required: true },
      { name: "轻薄外套", category: "clothing", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
    nearbyFrom: ["大理", "丽江"],
    nearbyDistance: "高铁2小时",
    holidayWarning: "国庆/五一石林人挤人",
    holidayAlternative: "九乡溶洞人少",
  },
  {
    id: "haerbin",
    name: "哈尔滨",
    province: "黑龙江",
    tagline: "东方莫斯科，冰雪之城",
    gradient: "from-blue-300 via-cyan-200 to-white-100",
    isNiche: false,
    destTypes: ["ancient_city", "food_city"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["winter", "summer"],
    bestTime: "12-2月(冰雪节) / 6-8月(避暑)",
    duration: "3-4天",
    budget: "人均1500-3000元",
    transportHub: "太平机场/哈尔滨站",
    coreTip: "冰雪大世界门票贵但值得，冬季保暖必备",
    funSpots: [
      { name: "冰雪大世界", tagline: "冰雪奇观", ticket: "300元", duration: "4-5小时", bestTime: "下午入园看夜景", tips: "12月底-2月初开放，带暖宝宝", priority: "must" },
      { name: "中央大街", tagline: "百年老街", ticket: "免费", duration: "2-3小时", bestTime: "傍晚", tips: "俄式建筑，马迭尔冰棍必吃", priority: "must" },
      { name: "圣索菲亚大教堂", tagline: "拜占庭建筑", ticket: "免费(外观)", duration: "1小时", bestTime: "白天", tips: "内部是建筑艺术馆", priority: "must" },
      { name: "太阳岛", tagline: "雪博会", ticket: "120元", duration: "半天", bestTime: "上午", tips: "冬季雪雕，夏季避暑", priority: "niche" },
    ],
    food: [
      { name: "马迭尔冰棍", pricePerPerson: "5-10元", howToEat: "奶味浓郁，越冷越好吃", pitfall: "中央大街排队最长" },
      { name: "锅包肉", pricePerPerson: "40-60元", howToEat: "外酥里嫩，酸甜口", pitfall: "老厨家是发源地" },
      { name: "东北乱炖", pricePerPerson: "50-80元", howToEat: "猪肉粉条白菜一锅炖", pitfall: "分量超大，别点多了" },
      { name: "红肠", pricePerPerson: "30-50元", howToEat: "烟熏风味，冷吃", pitfall: "秋林红肠最正宗" },
    ],
    foodAreas: [
      { name: "中央大街", location: "道里区", bestTime: "全天", direction: "俄式西餐+小吃" },
      { name: "老道外", location: "道外区", bestTime: "午餐/晚餐", direction: "老哈尔滨风味" },
    ],
    shopping: [
      { name: "中央大街", category: "mall", duration: "2-3小时", highlight: "百年商业街，俄式商品", forWho: "购物/拍照" },
      { name: "秋林公司", category: "mall", duration: "1-2小时", highlight: "老字号，红肠特产", forWho: "购物" },
    ],
    pitfalls: [
      { category: "scenic", content: "冰雪大世界门票贵，但值得" },
      { category: "traffic", content: "冬季路滑，穿防滑鞋" },
      { category: "general", content: "冬季零下20-30度，保暖装备必备" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["圣索菲亚大教堂"], afternoon: ["中央大街"], evening: ["冰雪大世界"], walkLevel: "约1.5万步", transport: "地铁+打车", nearbyFood: "中央大街" },
        { label: "Day2", morning: ["太阳岛"], afternoon: ["老道外"], evening: ["返程"], walkLevel: "约1万步", transport: "打车", nearbyFood: "老道外" },
      ],
      intense: [
        { label: "Day1", morning: ["圣索菲亚大教堂"], afternoon: ["中央大街"], evening: ["冰雪大世界"], walkLevel: "约2万步", transport: "地铁+打车", nearbyFood: "中央大街" },
        { label: "Day2", morning: ["太阳岛"], afternoon: ["东北虎林园"], evening: ["老道外"], walkLevel: "约1.5万步", transport: "打车", nearbyFood: "老道外" },
        { label: "Day3", morning: ["伏尔加庄园"], afternoon: ["果戈里大街"], evening: ["返程"], walkLevel: "约1.5万步", transport: "打车", nearbyFood: "果戈里大街" },
      ],
    },
    packingList: [
      { name: "羽绒服", category: "clothing", required: true },
      { name: "保暖内衣", category: "clothing", required: true },
      { name: "防滑鞋", category: "clothing", required: true },
      { name: "暖宝宝", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
  },
  {
    id: "yinchuan",
    name: "银川",
    province: "宁夏",
    tagline: "塞上江南，西夏古都",
    gradient: "from-yellow-300 via-amber-200 to-orange-100",
    isNiche: false,
    destTypes: ["ancient_city", "nature"],
    durationRange: "4-7d",
    budgetRange: "budget",
    seasons: ["spring", "autumn"],
    bestTime: "4-5月 / 9-10月",
    duration: "3-4天",
    budget: "人均1000-2000元",
    transportHub: "河东机场/银川站",
    coreTip: "西夏王陵+贺兰山岩画+沙湖，西北风情",
    funSpots: [
      { name: "西夏王陵", tagline: "东方金字塔", ticket: "75元", duration: "3-4小时", bestTime: "上午", tips: "西夏历史博物馆值得看", priority: "must" },
      { name: "贺兰山岩画", tagline: "史前艺术", ticket: "70元", duration: "3-4小时", bestTime: "上午", tips: "远古人类岩画，世界之最", priority: "must" },
      { name: "沙湖", tagline: "沙漠绿洲", ticket: "100元", duration: "半天", bestTime: "全天", tips: "沙漠+湖泊，骑骆驼", priority: "must" },
      { name: "镇北堡影视城", tagline: "大话西游拍摄地", ticket: "100元", duration: "半天", bestTime: "下午", tips: "明城+清城，拍照打卡", priority: "niche" },
    ],
    food: [
      { name: "手抓羊肉", pricePerPerson: "80-120元", howToEat: "宁夏滩羊，鲜嫩无膻味", pitfall: "老毛手抓最出名" },
      { name: "羊杂碎", pricePerPerson: "20-30元", howToEat: "羊头肉+羊杂，汤鲜", pitfall: "早餐最佳" },
      { name: "烩小吃", pricePerPerson: "15-25元", howToEat: "夹板、丸子、焖饼一锅烩", pitfall: "银川特色" },
      { name: "蒿子面", pricePerPerson: "10-15元", howToEat: "中卫特色，酸辣", pitfall: "中卫蒿子面最正宗" },
    ],
    foodAreas: [
      { name: "新华街", location: "兴庆区", bestTime: "午餐/晚餐", direction: "本地小吃" },
      { name: "怀远夜市", location: "西夏区", bestTime: "夜宵", direction: "夜市小吃" },
    ],
    shopping: [
      { name: "新华街", category: "old_street", duration: "1-2小时", highlight: "商业步行街", forWho: "散步" },
    ],
    pitfalls: [
      { category: "scenic", content: "景点间距离远，建议包车" },
      { category: "traffic", content: "公共交通不便" },
      { category: "general", content: "西北干燥，多喝水，带润唇膏" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["西夏王陵"], afternoon: ["贺兰山岩画"], evening: ["怀远夜市"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "怀远夜市" },
        { label: "Day2", morning: ["沙湖"], afternoon: ["镇北堡影视城"], evening: ["返程"], walkLevel: "约1万步", transport: "包车", nearbyFood: "市区" },
      ],
      intense: [
        { label: "Day1", morning: ["西夏王陵"], afternoon: ["贺兰山岩画"], evening: ["怀远夜市"], walkLevel: "约2万步", transport: "包车", nearbyFood: "怀远夜市" },
        { label: "Day2", morning: ["沙湖"], afternoon: ["沙湖"], evening: ["市区"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "新华街" },
        { label: "Day3", morning: ["镇北堡影视城"], afternoon: ["南关清真大寺"], evening: ["返程"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "市区" },
      ],
    },
    packingList: [
      { name: "防晒霜", category: "gear", required: true },
      { name: "润唇膏", category: "gear", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
  },
  {
    id: "lanzhou",
    name: "兰州",
    province: "甘肃",
    tagline: "黄河之城，拉面之都",
    gradient: "from-yellow-400 via-orange-300 to-red-200",
    isNiche: false,
    destTypes: ["food_city", "nature"],
    durationRange: "4-7d",
    budgetRange: "budget",
    seasons: ["spring", "autumn"],
    bestTime: "5-10月",
    duration: "2-3天",
    budget: "人均800-1500元",
    transportHub: "中川机场/兰州西站",
    coreTip: "牛肉面早餐必吃，黄河风情线散步",
    funSpots: [
      { name: "黄河风情线", tagline: "百里黄河", ticket: "免费", duration: "3-4小时", bestTime: "傍晚", tips: "中山桥+水车博览园", priority: "must" },
      { name: "中山桥", tagline: "天下黄河第一桥", ticket: "免费", duration: "1小时", bestTime: "傍晚", tips: "百年铁桥，夜景更美", priority: "must" },
      { name: "白塔山", tagline: "兰州地标", ticket: "免费", duration: "2-3小时", bestTime: "上午", tips: "俯瞰黄河+兰州城", priority: "must" },
      { name: "甘肃省博物馆", tagline: "丝路文化", ticket: "免费", duration: "3-4小时", bestTime: "上午", tips: "马踏飞燕，丝路文明", priority: "niche" },
    ],
    food: [
      { name: "牛肉面", pricePerPerson: "8-15元", howToEat: "一清二白三红四绿五黄", pitfall: "马子禄/吾穆勒最正宗" },
      { name: "手抓羊肉", pricePerPerson: "60-100元", howToEat: "甘肃滩羊，鲜嫩", pitfall: "阿西娅最出名" },
      { name: "酿皮子", pricePerPerson: "8-12元", howToEat: "酸辣爽口", pitfall: "街头小吃" },
      { name: "甜醅子", pricePerPerson: "5-10元", howToEat: "青稞发酵，甜香", pitfall: "夏季解暑" },
    ],
    foodAreas: [
      { name: "张掖路", location: "城关区", bestTime: "全天", direction: "商业步行街+小吃" },
      { name: "正宁路夜市", location: "城关区", bestTime: "夜宵", direction: "夜市小吃" },
    ],
    shopping: [
      { name: "张掖路", category: "old_street", duration: "2-3小时", highlight: "商业步行街", forWho: "散步/购物" },
    ],
    pitfalls: [
      { category: "food", content: "牛肉面早餐最正宗，下午别去" },
      { category: "traffic", content: "早晚高峰拥堵" },
      { category: "general", content: "西北干燥，多喝水" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["牛肉面早餐"], afternoon: ["甘肃省博物馆"], evening: ["黄河风情线"], walkLevel: "约1.5万步", transport: "公交+步行", nearbyFood: "张掖路" },
        { label: "Day2", morning: ["白塔山"], afternoon: ["中山桥"], evening: ["正宁路夜市"], walkLevel: "约1.5万步", transport: "公交+步行", nearbyFood: "正宁路夜市" },
      ],
      intense: [
        { label: "Day1", morning: ["牛肉面早餐"], afternoon: ["甘肃省博物馆"], evening: ["黄河风情线"], walkLevel: "约2万步", transport: "公交+步行", nearbyFood: "张掖路" },
        { label: "Day2", morning: ["白塔山"], afternoon: ["五泉山"], evening: ["正宁路夜市"], walkLevel: "约2万步", transport: "公交+步行", nearbyFood: "正宁路夜市" },
        { label: "Day3", morning: ["兴隆山"], afternoon: ["返程"], evening: ["沿途"], walkLevel: "约2万步", transport: "包车", nearbyFood: "沿途" },
      ],
    },
    packingList: [
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "润唇膏", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
  },
];
