import type { CityGuide } from "./types";

// 小众秘境目的地
export const nicheCities: CityGuide[] = [
  {
    id: "yading",
    name: "稻城亚丁",
    province: "四川",
    tagline: "最后的香格里拉",
    gradient: "from-sky-400 via-indigo-200 to-green-200",
    isNiche: true,
    destTypes: ["mountain", "nature", "hiking"],
    durationRange: "4-7d",
    budgetRange: "luxury",
    seasons: ["autumn"],
    bestTime: "9-10月(秋色) / 5-6月(花海)",
    duration: "5-7天",
    budget: "人均3000-5000元",
    transportHub: "稻城亚丁机场/成都出发自驾",
    coreTip: "海拔4000米+，高反是最大挑战，前两天别剧烈运动",
    funSpots: [
      { name: "三神山(仙乃日/央迈勇/夏诺多吉)", tagline: "藏传佛教圣山", ticket: "146元+观光车120元", duration: "2天", bestTime: "10月秋色最绝", tips: "天气决定一切，预留2天以防天气不好", priority: "must" },
      { name: "牛奶海+五色海", tagline: "高原海子", ticket: "含在门票内", duration: "4-5小时(徒步)", bestTime: "上午天气好时", tips: "最后1公里坡度极陡，量力而行", priority: "must" },
      { name: "洛绒牛场", tagline: "雪山草甸", ticket: "含在门票内", duration: "2小时", bestTime: "上午光线好", tips: "观光车终点，徒步起点", priority: "niche" },
    ],
    food: [
      { name: "酥油茶", pricePerPerson: "5-10元", howToEat: "咸口暖身，高反缓解", pitfall: "第一次喝可能不习惯" },
      { name: "牦牛肉", pricePerPerson: "50-80元", howToEat: "风干和炖煮都试试", pitfall: "别在景区买，稻城县城更便宜" },
      { name: "青稞饼", pricePerPerson: "5-8元", howToEat: "蘸酥油茶吃，藏族主食", pitfall: "口感偏硬，配茶才好吃" },
    ],
    foodAreas: [
      { name: "香格里拉镇(日瓦)", location: "亚丁景区门口", bestTime: "三餐", direction: "景区补给大本营，选择不多但够吃" },
      { name: "稻城县城", location: "稻城县城", bestTime: "进山前/出山后", direction: "补给+美食，比镇上丰富" },
    ],
    shopping: [
      { name: "稻城县城", category: "old_street", duration: "1小时", highlight: "藏族手工艺品和特产", forWho: "淘货" },
    ],
    pitfalls: [
      { category: "general", content: "海拔4000米+，高反是真实威胁，红景天提前1周吃" },
      { category: "general", content: "昼夜温差极大，夏天白天20度晚上0度" },
      { category: "traffic", content: "从成都自驾需2天，路况复杂需老司机" },
      { category: "general", content: "紫外线极强，防晒霜SPF50+不够还需物理防晒" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["成都→康定(自驾)"], afternoon: ["康定休整适应海拔"], evening: ["康定住宿"], walkLevel: "约3千步", transport: "自驾", nearbyFood: "康定城区" },
        { label: "Day2", morning: ["康定→稻城"], afternoon: ["稻城休整"], evening: ["稻城县城"], walkLevel: "约3千步", transport: "自驾", nearbyFood: "稻城县城" },
        { label: "Day3", morning: ["亚丁景区→冲古寺→珍珠海"], afternoon: ["珍珠海→返回"], evening: ["香格里拉镇休息"], walkLevel: "约8千步", transport: "观光车+步行", nearbyFood: "镇上餐厅" },
        { label: "Day4", morning: ["洛绒牛场→牛奶海"], afternoon: ["五色海(体力允许)"], evening: ["返回稻城"], walkLevel: "约1.5万步", transport: "观光车+徒步", nearbyFood: "稻城县城" },
      ],
      intense: [
        { label: "Day1", morning: ["成都→新都桥(自驾)"], afternoon: ["新都桥→稻城"], evening: ["稻城县城"], walkLevel: "约2千步", transport: "自驾", nearbyFood: "稻城县城" },
        { label: "Day2", morning: ["亚丁短线(冲古寺+珍珠海)"], afternoon: ["适应海拔+休整"], evening: ["香格里拉镇"], walkLevel: "约6千步", transport: "观光车+步行", nearbyFood: "镇上餐厅" },
        { label: "Day3", morning: ["洛绒牛场→牛奶海→五色海"], afternoon: ["继续徒步或返回"], evening: ["稻城县城"], walkLevel: "约2万步", transport: "观光车+徒步", nearbyFood: "稻城县城" },
      ],
    },
    packingList: [
      { name: "厚羽绒服", category: "clothing", required: true },
      { name: "登山鞋", category: "clothing", required: true },
      { name: "氧气瓶", category: "medicine", required: true },
      { name: "红景天(提前1周)", category: "medicine", required: true },
      { name: "防晒霜SPF50+", category: "gear", required: true },
      { name: "墨镜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "登山杖", category: "gear", required: false },
    ],
  },
  {
    id: "zhaoxing",
    name: "肇兴侗寨",
    province: "贵州",
    tagline: "鼓楼之乡，时光慢递",
    gradient: "from-teal-300 via-emerald-200 to-amber-100",
    isNiche: true,
    destTypes: ["ethnic", "ancient_city", "nature"],
    durationRange: "4-7d",
    budgetRange: "budget",
    seasons: ["spring", "summer", "autumn"],
    bestTime: "4-10月",
    duration: "3-4天",
    budget: "人均600-1200元",
    transportHub: "从江站(高铁)/贵阳转车",
    coreTip: "这里没有商业化的喧嚣，请尊重当地侗族生活习惯",
    funSpots: [
      { name: "肇兴侗寨五座鼓楼", tagline: "世界最大侗族村寨", ticket: "80元", duration: "半天", bestTime: "清晨和傍晚最安静", tips: "每座鼓楼代表一个团，各有特色", priority: "must" },
      { name: "堂安梯田", tagline: "云端梯田", ticket: "免费", duration: "3-4小时", bestTime: "日出时分", tips: "从肇兴徒步上堂安约2小时，景色绝美", priority: "must" },
      { name: "侗族大歌表演", tagline: "世界非遗", ticket: "免费(定时演出)", duration: "1小时", bestTime: "晚上8点", tips: "多声部无指挥合唱，世界级非遗", priority: "must" },
    ],
    food: [
      { name: "酸汤鱼", pricePerPerson: "30-50元", howToEat: "红酸汤+稻花鱼，贵州灵魂", pitfall: "酸汤是发酵的，第一次可能不习惯" },
      { name: "油茶", pricePerPerson: "5-10元", howToEat: "茶叶+花生+米花+葱姜", pitfall: "侗族早餐标配，咸口" },
      { name: "糯米饭", pricePerPerson: "5-10元", howToEat: "手抓着吃，配酸汤或腌肉", pitfall: "很顶饱，别吃太多" },
    ],
    foodAreas: [
      { name: "寨内主街", location: "肇兴侗寨内", bestTime: "三餐", direction: "沿街小馆子，酸汤鱼为主" },
    ],
    shopping: [
      { name: "侗寨手工艺品", category: "old_street", duration: "1小时", highlight: "侗布、银饰、刺绣", forWho: "淘货/文艺" },
    ],
    pitfalls: [
      { category: "traffic", content: "从江高铁站到肇兴需转车约40分钟" },
      { category: "general", content: "尊重侗族风俗，鼓楼内不要大声喧哗" },
      { category: "general", content: "住宿条件较简陋，不要期待星级酒店" },
      { category: "general", content: "带现金，部分小店不支持电子支付" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["到达肇兴"], afternoon: ["寨内漫步+五座鼓楼"], evening: ["侗族大歌表演"], walkLevel: "约6千步", transport: "步行", nearbyFood: "寨内小馆" },
        { label: "Day2", morning: ["徒步堂安梯田(2小时上山)"], afternoon: ["堂安村午餐+梯田拍照"], evening: ["返回肇兴+油茶"], walkLevel: "约1.2万步", transport: "徒步", nearbyFood: "堂安农家" },
        { label: "Day3", morning: ["周边岜沙苗寨(可选)"], afternoon: ["返回肇兴"], evening: ["告别晚餐"], walkLevel: "约5千步", transport: "包车", nearbyFood: "寨内" },
      ],
      intense: [],
    },
    packingList: [
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "防蚊虫药", category: "medicine", required: true },
      { name: "雨衣", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "现金", category: "docs", required: true },
    ],
  },
  {
    id: "wuyuan",
    name: "婺源",
    province: "江西",
    tagline: "中国最美乡村，油菜花海",
    gradient: "from-yellow-300 via-green-200 to-sky-200",
    isNiche: true,
    destTypes: ["nature", "ancient_city"],
    durationRange: "4-7d",
    budgetRange: "budget",
    seasons: ["spring"],
    bestTime: "3月中旬-4月上旬(油菜花)",
    duration: "3-4天",
    budget: "人均800-1500元",
    transportHub: "婺源站(高铁)/景德镇转车",
    coreTip: "油菜花花期只有3周，3月中旬-4月初，错过再等一年",
    funSpots: [
      { name: "江岭梯田油菜花", tagline: "婺源最壮观的花海", ticket: "80元", duration: "3-4小时", bestTime: "清晨看云海+花海", tips: "是婺源赏花第一站，必须早起", priority: "must" },
      { name: "篁岭晒秋", tagline: "最美中国符号", ticket: "120元+索道", duration: "3-4小时", bestTime: "四季不同景", tips: "晒秋是秋景，春天看花，夏天看绿", priority: "must" },
      { name: "思溪延村", tagline: "徽派古村落", ticket: "60元", duration: "2小时", bestTime: "上午人少", tips: "《聊斋》取景地，古建筑精美", priority: "niche" },
    ],
    food: [
      { name: "荷包红鲤鱼", pricePerPerson: "30-50元", howToEat: "清蒸最鲜，婺源招牌菜", pitfall: "别买景区门口的，村里吃更实惠" },
      { name: "糊豆腐", pricePerPerson: "10-15元", howToEat: "徽菜经典，开胃又暖身", pitfall: "看似平淡实际很香" },
      { name: "清明果", pricePerPerson: "5-8元", howToEat: "艾草+糯米+馅料，春天限定", pitfall: "只有3-4月才有最正宗的" },
    ],
    foodAreas: [
      { name: "各村落农家乐", location: "景区内村落", bestTime: "午餐/晚餐", direction: "住在哪吃到哪，农家菜最实在" },
    ],
    shopping: [
      { name: "篁岭天街", category: "old_street", duration: "1-2小时", highlight: "徽派建筑+文创小店", forWho: "拍照/购物" },
    ],
    pitfalls: [
      { category: "general", content: "花期只有3周，务必提前查当年花期" },
      { category: "traffic", content: "各景点分散，建议自驾或包车" },
      { category: "general", content: "3月雨多带伞，花海配烟雨更有意境" },
      { category: "general", content: "住宿旺季涨价3倍+，提前1个月订" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["到达婺源→江岭梯田"], afternoon: ["江岭花海拍照"], evening: ["住江岭附近"], walkLevel: "约8千步", transport: "自驾/包车", nearbyFood: "农家乐" },
        { label: "Day2", morning: ["篁岭(索道上山)"], afternoon: ["篁岭天街+晒秋"], evening: ["住篁岭或县城"], walkLevel: "约1万步", transport: "索道+步行", nearbyFood: "篁岭天街" },
        { label: "Day3", morning: ["思溪延村"], afternoon: ["彩虹桥→返程"], evening: [""], walkLevel: "约6千步", transport: "自驾/包车", nearbyFood: "农家乐" },
      ],
      intense: [],
    },
    packingList: [
      { name: "雨衣/雨伞", category: "gear", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
  },
  {
    id: "ejina",
    name: "额济纳",
    province: "内蒙古",
    tagline: "三千年的胡杨，三千年的守望",
    gradient: "from-amber-400 via-orange-300 to-red-300",
    isNiche: true,
    destTypes: ["nature", "hiking"],
    durationRange: "4-7d",
    budgetRange: "luxury",
    seasons: ["autumn"],
    bestTime: "10月1日-20日(胡杨林金秋)",
    duration: "4-5天",
    budget: "人均3000-5000元",
    transportHub: "额济纳旗机场/银川转车",
    coreTip: "胡杨林最佳观赏期只有20天，10月初-中旬，错过再等一年",
    funSpots: [
      { name: "额济纳胡杨林", tagline: "世界三大胡杨林之一", ticket: "240元(八道桥联票)", duration: "1天", bestTime: "10月1-15日", tips: "二道桥拍倒影，四道桥拍人像，七道桥最原始", priority: "must" },
      { name: "居延海日出", tagline: "沙漠中的海子", ticket: "60元", duration: "2-3小时", bestTime: "清晨6点看日出", tips: "必须早起！日出瞬间水面金色太美", priority: "must" },
      { name: "黑城遗址", tagline: "西夏古城废墟", ticket: "含在胡杨林联票", duration: "1-2小时", bestTime: "下午光线斜射", tips: "苍凉感十足，拍照极有氛围", priority: "niche" },
    ],
    food: [
      { name: "手把肉", pricePerPerson: "40-60元", howToEat: "手撕着吃，蘸蒜泥酱油", pitfall: "份量大，2人点1斤足够" },
      { name: "奶茶+奶皮子", pricePerPerson: "10-20元", howToEat: "咸奶茶配奶皮子，蒙古早餐", pitfall: "咸口奶茶，跟甜奶茶完全不同" },
      { name: "烤全羊", pricePerPerson: "人均80-120元", howToEat: "4人起吃，配蒙古包子", pitfall: "需提前3小时预定，不是随时有" },
    ],
    foodAreas: [
      { name: "达镇主街", location: "额济纳旗达来呼布镇", bestTime: "三餐", direction: "小镇不大，主街餐厅集中" },
    ],
    shopping: [
      { name: "达镇特产店", category: "old_street", duration: "30分钟", highlight: "肉苁蓉、锁阳等沙漠特产", forWho: "淘货" },
    ],
    pitfalls: [
      { category: "general", content: "最佳观赏期只有20天，务必提前查当年叶黄时间" },
      { category: "general", content: "住宿旺季一房难求且价格翻3倍+，提前2个月订" },
      { category: "general", content: "沙漠温差极大，白天25度晚上0度" },
      { category: "traffic", content: "距银川800公里自驾10小时，建议飞额济纳机场" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["到达额济纳"], afternoon: ["达镇休息适应"], evening: ["主街觅食"], walkLevel: "约3千步", transport: "飞机/自驾", nearbyFood: "达镇主街" },
        { label: "Day2", morning: ["胡杨林(二道桥-四道桥)"], afternoon: ["胡杨林(五道桥-七道桥)"], evening: ["八道桥看日落"], walkLevel: "约1.5万步", transport: "景区摆渡车+步行", nearbyFood: "自带干粮" },
        { label: "Day3", morning: ["居延海日出(5点出发)"], afternoon: ["黑城遗址"], evening: ["达镇晚餐"], walkLevel: "约8千步", transport: "包车", nearbyFood: "达镇主街" },
      ],
      intense: [],
    },
    packingList: [
      { name: "厚羽绒服", category: "clothing", required: true },
      { name: "保温杯", category: "gear", required: true },
      { name: "防晒霜+墨镜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "零食干粮", category: "gear", required: true },
    ],
  },
  {
    id: "kanas",
    name: "喀纳斯",
    province: "新疆",
    tagline: "上帝的后花园",
    gradient: "from-emerald-400 via-teal-300 to-sky-300",
    isNiche: true,
    destTypes: ["nature", "mountain", "hiking"],
    durationRange: "8d+",
    budgetRange: "premium",
    seasons: ["autumn"],
    bestTime: "9月中旬-10月初(秋色)",
    duration: "5-7天",
    budget: "人均5000-8000元",
    transportHub: "阿勒泰机场/乌鲁木齐出发",
    coreTip: "9月秋色只有2周窗口期，务必提前查当年时间",
    funSpots: [
      { name: "喀纳斯湖", tagline: "神秘的高山湖泊", ticket: "185元(含区间车)", duration: "1天", bestTime: "9月秋色最美", tips: "三湾(卧龙湾/月亮湾/神仙湾)必徒步", priority: "must" },
      { name: "禾木村", tagline: "图瓦人村落", ticket: "60元+区间车52元", duration: "1-2天", bestTime: "清晨晨雾+9月秋色", tips: "住一晚看晨雾，人间仙境", priority: "must" },
      { name: "白哈巴", tagline: "西北第一村", ticket: "50元+区间车", duration: "半天", bestTime: "傍晚看日落", tips: "边防证在景区办，需带身份证", priority: "niche" },
    ],
    food: [
      { name: "大盘鸡", pricePerPerson: "40-60元", howToEat: "鸡肉+土豆+皮带面，新疆灵魂", pitfall: "2人点小盘，份量惊人" },
      { name: "手抓饭", pricePerPerson: "25-40元", howToEat: "羊肉+胡萝卜+洋葱焖饭", pitfall: "午饭才有，卖完即止" },
      { name: "烤羊肉串", pricePerPerson: "10-20元", howToEat: "肥瘦相间最香", pitfall: "景区比镇上贵1倍" },
    ],
    foodAreas: [
      { name: "贾登峪(景区门口)", location: "喀纳斯景区入口", bestTime: "三餐", direction: "补给大本营，选择有限" },
      { name: "禾木村内", location: "禾木村", bestTime: "三餐", direction: "图瓦人家庭旅馆+小餐馆" },
    ],
    shopping: [
      { name: "禾木村", category: "old_street", duration: "1小时", highlight: "图瓦人手工艺品", forWho: "淘货" },
    ],
    pitfalls: [
      { category: "general", content: "9月秋色窗口期只有2周，提前查时间" },
      { category: "general", content: "景区物价贵2-3倍，自带干粮很必要" },
      { category: "traffic", content: "乌鲁木齐到喀纳斯自驾10小时，建议飞阿勒泰" },
      { category: "general", content: "早晚温差20度+，四季衣服都带上" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["阿勒泰→贾登峪"], afternoon: ["入住休整"], evening: ["贾登峪晚餐"], walkLevel: "约2千步", transport: "包车", nearbyFood: "贾登峪" },
        { label: "Day2", morning: ["喀纳斯湖+三湾徒步"], afternoon: ["观鱼台俯瞰全湖"], evening: ["返回贾登峪"], walkLevel: "约1.5万步", transport: "区间车+步行", nearbyFood: "自带干粮" },
        { label: "Day3", morning: ["禾木村"], afternoon: ["禾木漫步+骑马"], evening: ["住禾木看星空"], walkLevel: "约8千步", transport: "区间车+步行", nearbyFood: "禾木村内" },
        { label: "Day4", morning: ["禾木晨雾(必看)"], afternoon: ["白哈巴(可选)"], evening: ["返回"], walkLevel: "约6千步", transport: "区间车", nearbyFood: "贾登峪" },
      ],
      intense: [],
    },
    packingList: [
      { name: "厚羽绒服", category: "clothing", required: true },
      { name: "登山鞋", category: "clothing", required: true },
      { name: "保温杯", category: "gear", required: true },
      { name: "防晒霜+墨镜", category: "gear", required: true },
      { name: "身份证(边防证用)", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "零食干粮", category: "gear", required: true },
    ],
  },
  {
    id: "gannan",
    name: "甘南",
    province: "甘肃",
    tagline: "九色甘南，藏区秘境",
    gradient: "from-green-400 via-emerald-300 to-blue-200",
    isNiche: true,
    destTypes: ["nature", "ethnic"],
    durationRange: "4-7d",
    budgetRange: "budget",
    seasons: ["summer", "autumn"],
    bestTime: "6-9月",
    duration: "5-7天",
    budget: "人均2000-3500元",
    transportHub: "兰州自驾/合作机场",
    coreTip: "拉卜楞寺+扎尕那+郎木寺，藏传佛教文化",
    funSpots: [
      { name: "拉卜楞寺", tagline: "藏传佛教六大寺院", ticket: "40元", duration: "3-4小时", bestTime: "上午", tips: "世界最长转经廊", priority: "must" },
      { name: "扎尕那", tagline: "东方小瑞士", ticket: "80元", duration: "1天", bestTime: "全天", tips: "石城+仙女滩+一线天", priority: "must" },
      { name: "郎木寺", tagline: "东方小瑞士", ticket: "30元", duration: "半天", bestTime: "上午", tips: "天葬台(尊重当地文化)", priority: "must" },
      { name: "桑科草原", tagline: "草原风光", ticket: "免费", duration: "2-3小时", bestTime: "下午", tips: "骑马体验", priority: "niche" },
    ],
    food: [
      { name: "藏式糌粑", pricePerPerson: "10-15元", howToEat: "青稞面，酥油茶拌食", pitfall: "当地民宿" },
      { name: "牦牛酸奶", pricePerPerson: "10-15元", howToEat: "浓稠，加白糖", pitfall: "当地特色" },
      { name: "手抓羊肉", pricePerPerson: "60-100元", howToEat: "鲜嫩无膻味", pitfall: "当地餐厅" },
    ],
    foodAreas: [
      { name: "夏河县城", location: "夏河县", bestTime: "午餐/晚餐", direction: "藏餐+川菜" },
    ],
    shopping: [],
    pitfalls: [
      { category: "general", content: "海拔3000-3500米，轻微高反" },
      { category: "traffic", content: "景点间距离远，建议包车" },
      { category: "scenic", content: "扎尕那路况差，SUV最佳" },
      { category: "general", content: "尊重当地宗教文化" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["兰州→夏河"], afternoon: ["拉卜楞寺"], evening: ["夏河县城"], walkLevel: "约1万步", transport: "包车", nearbyFood: "夏河县城" },
        { label: "Day2", morning: ["桑科草原"], afternoon: ["郎木寺"], evening: ["郎木寺镇"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "郎木寺镇" },
        { label: "Day3", morning: ["扎尕那"], afternoon: ["扎尕那"], evening: ["扎尕那村"], walkLevel: "约2万步", transport: "包车", nearbyFood: "扎尕那村" },
        { label: "Day4", morning: ["扎尕那"], afternoon: ["返程"], evening: ["沿途"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "沿途" },
      ],
      intense: [],
    },
    packingList: [
      { name: "厚外套", category: "clothing", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "防晒霜+墨镜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
  },
  {
    id: "enshi",
    name: "恩施",
    province: "湖北",
    tagline: "中国仙本那，秘境恩施",
    gradient: "from-green-400 via-teal-300 to-cyan-200",
    isNiche: true,
    destTypes: ["nature", "ethnic"],
    durationRange: "4-7d",
    budgetRange: "budget",
    seasons: ["spring", "summer", "autumn"],
    bestTime: "4-10月",
    duration: "4-5天",
    budget: "人均1500-2500元",
    transportHub: "恩施机场/恩施站",
    coreTip: "屏山峡谷+恩施大峡谷+腾龙洞，土家族文化",
    funSpots: [
      { name: "屏山峡谷", tagline: "中国仙本那", ticket: "210元", duration: "半天", bestTime: "上午", tips: "悬浮船拍照，水清见底", priority: "must" },
      { name: "恩施大峡谷", tagline: "东方科罗拉多", ticket: "170元", duration: "1天", bestTime: "全天", tips: "一炷香+绝壁栈道", priority: "must" },
      { name: "腾龙洞", tagline: "世界特级溶洞", ticket: "150元", duration: "半天", bestTime: "上午", tips: "洞内有激光秀", priority: "must" },
      { name: "土司城", tagline: "土家族文化", ticket: "50元", duration: "2-3小时", bestTime: "上午", tips: "土家族建筑+表演", priority: "niche" },
    ],
    food: [
      { name: "张关合渣", pricePerPerson: "30-50元", howToEat: "黄豆磨制，配小菜", pitfall: "恩施特色" },
      { name: "土家烧饼", pricePerPerson: "5-10元", howToEat: "酥脆，夹肉", pitfall: "街头小吃" },
      { name: "社饭", pricePerPerson: "15-25元", howToEat: "糯米+腊肉+野菜", pitfall: "土家族特色" },
    ],
    foodAreas: [
      { name: "舞阳坝", location: "恩施市", bestTime: "午餐/晚餐", direction: "本地小吃" },
    ],
    shopping: [],
    pitfalls: [
      { category: "traffic", content: "景点间距离远，建议包车" },
      { category: "scenic", content: "大峡谷徒步量大，穿舒适鞋" },
      { category: "general", content: "夏季避暑，带防晒" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["屏山峡谷"], afternoon: ["土司城"], evening: ["舞阳坝"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "舞阳坝" },
        { label: "Day2", morning: ["恩施大峡谷"], afternoon: ["恩施大峡谷"], evening: ["恩施市"], walkLevel: "约2.5万步", transport: "包车", nearbyFood: "恩施市" },
        { label: "Day3", morning: ["腾龙洞"], afternoon: ["返程"], evening: ["利川市"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "利川市" },
      ],
      intense: [
        { label: "Day1", morning: ["屏山峡谷"], afternoon: ["土司城"], evening: ["舞阳坝"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "舞阳坝" },
        { label: "Day2", morning: ["恩施大峡谷"], afternoon: ["恩施大峡谷"], evening: ["恩施市"], walkLevel: "约3万步", transport: "包车", nearbyFood: "恩施市" },
        { label: "Day3", morning: ["腾龙洞"], afternoon: ["清江画廊"], evening: ["恩施市"], walkLevel: "约2万步", transport: "包车", nearbyFood: "恩施市" },
        { label: "Day4", morning: ["梭布垭石林"], afternoon: ["返程"], evening: ["沿途"], walkLevel: "约1.5万步", transport: "包车", nearbyFood: "沿途" },
      ],
    },
    packingList: [
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
  },
  {
    id: "jingxi",
    name: "靖西",
    province: "广西",
    tagline: "中越边境山水画廊",
    gradient: "from-emerald-400 via-teal-200 to-cyan-100",
    isNiche: true,
    destTypes: ["nature", "ancient_city"],
    durationRange: "4-7d",
    budgetRange: "budget",
    seasons: ["spring", "summer", "autumn"],
    bestTime: "4-5月(碧水青山) / 7-8月(瀑布丰水期)",
    duration: "3-4天",
    budget: "人均800-1500元",
    transportHub: "靖西站/南宁出发自驾",
    coreTip: "边境地区随身携带身份证，丰水期瀑布最壮观，峡谷湿滑务必穿防滑鞋",
    funSpots: [
      {
        name: "通灵大峡谷",
        tagline: "亚洲单级落差最高瀑布",
        ticket: "115元(含接驳车)",
        duration: "3小时",
        bestTime: "夏季丰水期",
        tips: "全程徒步台阶较多，12月-次年2月枯水期水量极小，不推荐前往",
        priority: "must",
      },
      {
        name: "鹅泉",
        tagline: "西南三大名泉",
        ticket: "48元(早7点前免费入园)",
        duration: "2-3小时",
        bestTime: "清晨晨雾时分",
        tips: "十五孔古桥倒影绝美，可乘村民竹筏游湖，日出晨雾出片率最高",
        priority: "must",
      },
      {
        name: "旧州古镇",
        tagline: "中国绣球之乡",
        ticket: "48元(17点后免费入园)",
        duration: "2小时",
        bestTime: "傍晚光线柔和",
        tips: "600年壮乡古寨，可体验手工DIY绣球，感受原生态壮乡风情",
        priority: "niche",
      },
    ],
    food: [
      {
        name: "靖西卷筒粉",
        pricePerPerson: "3-5元/条",
        howToEat: "薄米皮裹肉馅豆角，淋本地黄皮酱，是本地人早餐灵魂",
        pitfall: "分量扎实，早餐吃1-2条即可，避免影响正餐",
      },
      {
        name: "靖西酸嘢",
        pricePerPerson: "5-15元/份",
        howToEat: "新鲜果蔬腌制，酸辣脆爽，解腻开胃，街头随处可见",
        pitfall: "酸度较高，肠胃敏感人群建议少量尝试",
      },
      {
        name: "壮家猪血肠",
        pricePerPerson: "10元/份",
        howToEat: "糯米与猪血灌制，煎制后外焦里嫩，撒椒盐食用",
        pitfall: "口感偏糯黏，趁热吃风味最佳，凉后易腥",
      },
    ],
    foodAreas: [
      {
        name: "靖西市区主山街",
        location: "靖西市区中心",
        bestTime: "早餐/午餐",
        direction: "本地老字号小吃聚集，平价地道，本地人常去",
      },
      {
        name: "旧州古镇内",
        location: "旧州古镇景区",
        bestTime: "午晚餐",
        direction: "壮家农家菜为主，临溪用餐环境好，选择不多",
      },
    ],
    shopping: [
      {
        name: "旧州绣球街",
        category: "old_street",
        duration: "1小时",
        highlight: "手工绣球、壮锦、五色糯米饭等壮族特产",
        forWho: "伴手礼/文艺淘货",
      },
    ],
    pitfalls: [
      { category: "general", content: "边境区域可能出现越南信号漂移，建议关闭数据漫游" },
      { category: "general", content: "峡谷瀑布区域湿滑多台阶，穿防滑鞋，雨季注意防范落石" },
      { category: "traffic", content: "景点分散无直达公交，建议包车出行，日均约300元" },
      { category: "general", content: "夏季紫外线强、蚊虫多，需做好防晒与防蚊虫准备" },
    ],
    itinerary: {
      easy: [
        {
          label: "Day1",
          morning: ["南宁/百色→靖西市区"],
          afternoon: ["旧州古镇逛游+绣球DIY体验"],
          evening: ["市区住宿+老街小吃"],
          walkLevel: "约5千步",
          transport: "自驾/大巴",
          nearbyFood: "靖西市区老街",
        },
        {
          label: "Day2",
          morning: ["鹅泉晨雾+古桥打卡"],
          afternoon: ["通灵大峡谷徒步观瀑"],
          evening: ["返回市区休息"],
          walkLevel: "约1万步",
          transport: "包车/自驾",
          nearbyFood: "景区周边农家菜",
        },
        {
          label: "Day3",
          morning: ["渠洋湖游船/环湖骑行"],
          afternoon: ["返程"],
          evening: [],
          walkLevel: "约4千步",
          transport: "自驾/大巴",
          nearbyFood: "渠洋湖周边农家乐",
        },
      ],
      intense: [
        {
          label: "Day1",
          morning: ["抵达靖西→鹅泉快速打卡"],
          afternoon: ["通灵大峡谷深度徒步"],
          evening: ["旧州古镇夜景+住宿"],
          walkLevel: "约1.2万步",
          transport: "包车/自驾",
          nearbyFood: "旧州古镇内",
        },
        {
          label: "Day2",
          morning: ["渠洋湖日出+游船"],
          afternoon: ["返程"],
          evening: [],
          walkLevel: "约6千步",
          transport: "自驾/大巴",
          nearbyFood: "渠洋湖周边",
        },
      ],
    },
    packingList: [
      { name: "防滑运动鞋", category: "clothing", required: true },
      { name: "防蚊虫药", category: "medicine", required: true },
      { name: "雨衣/雨伞", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "薄外套", category: "clothing", required: false },
    ],
  },
  {
    id: "libo",
    name: "荔波",
    province: "贵州",
    tagline: "地球腰带上的绿宝石",
    gradient: "from-emerald-500 via-teal-300 to-cyan-200",
    isNiche: true,
    destTypes: ["nature"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["spring", "summer", "autumn"],
    bestTime: "6-8月(水量充沛水色最蓝) / 4-5月(春水初盛人少)",
    duration: "3-4天",
    budget: "人均1200-1800元",
    transportHub: "荔波站/贵阳高铁直达/自驾",
    coreTip: "景区推荐西门进东门出全程下坡省力，夏季玩水注意防滑，雨季水量最大景色最佳",
    funSpots: [
      {
        name: "小七孔景区",
        tagline: "世界自然遗产水景秘境",
        ticket: "旺季170元(含观光车，2日有效)",
        duration: "1天",
        bestTime: "6-8月丰水期",
        tips: "西门进东门出最省力，卧龙潭、68级跌水、小七孔古桥必打卡",
        priority: "must",
      },
      {
        name: "茂兰喀斯特森林",
        tagline: "原生喀斯特森林秘境",
        ticket: "50元",
        duration: "半天",
        bestTime: "春夏绿意最浓",
        tips: "青龙潭徒步玩水，原生态无商业化，适合喜欢自然的游客",
        priority: "must",
      },
      {
        name: "大七孔天生桥",
        tagline: "东方凯旋门",
        ticket: "含在小七孔联票内",
        duration: "2小时",
        bestTime: "上午光线佳",
        tips: "峡谷雄奇险峻，天生桥是核心地标，步行难度低",
        priority: "niche",
      },
    ],
    food: [
      {
        name: "酸汤牛肉",
        pricePerPerson: "30-50元",
        howToEat: "本地小番茄发酵酸汤，配鲜牛肉与野菜，酸辣开胃",
        pitfall: "酸汤为发酵制成，初次食用可能觉得酸度偏高",
      },
      {
        name: "豆花烤鱼",
        pricePerPerson: "40-60元",
        howToEat: "江鱼先烤后炖，铺满嫩豆花，吸满汤汁鲜香入味",
        pitfall: "野生江鱼刺较多，食用时需注意细嚼慢咽",
      },
      {
        name: "冰镇杨梅汤",
        pricePerPerson: "5-8元/杯",
        howToEat: "本地杨梅熬制，冰镇酸甜解腻，夏日解暑神器",
        pitfall: "甜度较高，不喜甜可要求少糖",
      },
    ],
    foodAreas: [
      {
        name: "梦柳布依风情小镇",
        location: "小七孔东门旁",
        bestTime: "三餐",
        direction: "景区配套美食街，选择丰富，吃住一站式",
      },
      {
        name: "荔波县城美食街",
        location: "荔波县城",
        bestTime: "晚餐/夜宵",
        direction: "本地老字号聚集，性价比更高，夜宵烟火气浓",
      },
    ],
    shopping: [
      {
        name: "荔波古镇",
        category: "old_street",
        duration: "1小时",
        highlight: "布依族银饰、蜡染、青梅酒等特产",
        forWho: "伴手礼/文艺淘货",
      },
    ],
    pitfalls: [
      { category: "general", content: "夏季玩水区域湿滑，穿防滑鞋，深水区禁止擅自下水" },
      { category: "traffic", content: "景区观光车必买，景点间距远，徒步无法完成全程" },
      { category: "general", content: "林区蚊虫密集，尤其是茂兰景区，务必带强效防蚊虫药" },
      { category: "general", content: "雨季多阵雨，随身带雨衣，山区天气多变注意保暖" },
    ],
    itinerary: {
      easy: [
        {
          label: "Day1",
          morning: ["贵阳/都匀→荔波县城"],
          afternoon: ["大七孔景区轻松游览"],
          evening: ["县城住宿+美食街晚餐"],
          walkLevel: "约6千步",
          transport: "高铁/自驾+观光车",
          nearbyFood: "荔波县城美食街",
        },
        {
          label: "Day2",
          morning: ["小七孔西门入园→卧龙潭"],
          afternoon: ["68级跌水→水上森林→小七孔古桥"],
          evening: ["梦柳小镇住宿"],
          walkLevel: "约1.2万步",
          transport: "景区观光车+步行",
          nearbyFood: "梦柳小镇餐厅",
        },
        {
          label: "Day3",
          morning: ["茂兰喀斯特森林青龙潭徒步"],
          afternoon: ["返程"],
          evening: [],
          walkLevel: "约8千步",
          transport: "包车/自驾",
          nearbyFood: "茂兰周边农家乐",
        },
      ],
      intense: [
        {
          label: "Day1",
          morning: ["抵达荔波→小七孔全天深度游"],
          afternoon: ["大七孔顺路打卡"],
          evening: ["县城晚餐+住宿"],
          walkLevel: "约1.5万步",
          transport: "观光车+步行",
          nearbyFood: "梦柳小镇",
        },
        {
          label: "Day2",
          morning: ["茂兰喀斯特森林快速游览"],
          afternoon: ["返程"],
          evening: [],
          walkLevel: "约7千步",
          transport: "包车/自驾",
          nearbyFood: "茂兰农家乐",
        },
      ],
    },
    packingList: [
      { name: "防滑溯溪鞋", category: "clothing", required: true },
      { name: "防蚊虫药", category: "medicine", required: true },
      { name: "雨衣", category: "gear", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "换洗衣物", category: "clothing", required: false },
    ],
  },
  {
    id: "tengchong",
    name: "腾冲",
    province: "云南",
    tagline: "火山热海，极边第一城",
    gradient: "from-amber-400 via-orange-200 to-yellow-100",
    isNiche: true,
    destTypes: ["hot_spring", "ancient_city"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["spring", "autumn", "winter"],
    bestTime: "10-12月(银杏季) / 1-2月(温泉季)",
    duration: "4-5天",
    budget: "人均1500-2500元",
    transportHub: "腾冲驼峰机场/保山转车",
    coreTip: "国内罕见火山地热共生之地，泡温泉注意补充水分，银杏季需提前预订住宿",
    funSpots: [
      {
        name: "热海风景区",
        tagline: "中国地热温泉之王",
        ticket: "50元，观光车单程10元",
        duration: "3-4小时",
        bestTime: "上午游客少，蒸汽缭绕如仙境",
        tips: "大滚锅是地标，可体验温泉煮蛋，切勿直接触碰高温泉眼",
        priority: "must",
      },
      {
        name: "和顺古镇",
        tagline: "中国十大魅力名镇之首",
        ticket: "旺季70元/淡季55元",
        duration: "半天-1天",
        bestTime: "清晨傍晚人少安静",
        tips: "600年侨乡古镇，和顺图书馆、艾思奇故居值得深度游览",
        priority: "must",
      },
      {
        name: "火山地质公园",
        tagline: "中国最年轻火山群",
        ticket: "35元",
        duration: "2小时",
        bestTime: "上午光线好",
        tips: "可乘热气球俯瞰火山口，爬火山口台阶不多，难度低",
        priority: "niche",
      },
    ],
    food: [
      {
        name: "大救驾(炒饵块)",
        pricePerPerson: "15-25元",
        howToEat: "饵块配鸡蛋鲜肉蔬菜炒制，云南名小吃，传说救过永历帝",
        pitfall: "分量扎实，一份管饱，单人用餐别点太多",
      },
      {
        name: "腾冲土锅子",
        pricePerPerson: "50-80元",
        howToEat: "陶土锅炖煮排骨酥肉蔬菜，暖身暖胃，本地特色火锅",
        pitfall: "炖煮时间长，建议提前预订，越煮越入味",
      },
      {
        name: "稀豆粉",
        pricePerPerson: "8-15元",
        howToEat: "豌豆磨浆熬制，配油条饵丝，本地早餐标配",
        pitfall: "口感绵密豆香浓，第一次吃可能不习惯",
      },
    ],
    foodAreas: [
      {
        name: "和顺古镇食街",
        location: "和顺古镇内",
        bestTime: "三餐",
        direction: "古镇特色餐厅，环境雅致，适合边吃边逛",
      },
      {
        name: "腾冲市区官厅路",
        location: "腾冲市区老街区",
        bestTime: "早餐/夜宵",
        direction: "本地老字号聚集，性价比高，地道小吃多",
      },
    ],
    shopping: [
      {
        name: "和顺翡翠老街",
        category: "old_street",
        duration: "1小时",
        highlight: "翡翠、腾药、腾宣等本地特产",
        forWho: "伴手礼/收藏",
      },
    ],
    pitfalls: [
      { category: "general", content: "热海泉眼水温高达97℃，切勿触摸，避免高温烫伤" },
      { category: "general", content: "早晚温差大，秋冬需备厚外套，泡温泉请自带泳衣" },
      { category: "traffic", content: "景点分散，建议包车出行，日均300-500元" },
      { category: "general", content: "11月中下旬银杏季住宿紧张，需提前1-2周预订" },
    ],
    itinerary: {
      easy: [
        {
          label: "Day1",
          morning: ["抵达腾冲→和顺古镇入住"],
          afternoon: ["和顺古镇慢逛+图书馆/故居"],
          evening: ["古镇夜景+晚餐"],
          walkLevel: "约6千步",
          transport: "打车/包车",
          nearbyFood: "和顺古镇内餐厅",
        },
        {
          label: "Day2",
          morning: ["热海风景区游览"],
          afternoon: ["体验天然温泉泡浴"],
          evening: ["市区晚餐+住宿"],
          walkLevel: "约7千步",
          transport: "包车",
          nearbyFood: "热海周边/市区",
        },
        {
          label: "Day3",
          morning: ["火山地质公园打卡"],
          afternoon: ["北海湿地游览"],
          evening: ["返回市区"],
          walkLevel: "约5千步",
          transport: "包车",
          nearbyFood: "市区美食街",
        },
        {
          label: "Day4",
          morning: ["国殇墓园参观"],
          afternoon: ["返程"],
          evening: [],
          walkLevel: "约4千步",
          transport: "打车",
          nearbyFood: "市区",
        },
      ],
      intense: [
        {
          label: "Day1",
          morning: ["抵达腾冲→热海风景区"],
          afternoon: ["和顺古镇快速游览"],
          evening: ["古镇住宿+温泉"],
          walkLevel: "约1万步",
          transport: "包车",
          nearbyFood: "和顺古镇",
        },
        {
          label: "Day2",
          morning: ["火山地质公园→北海湿地"],
          afternoon: ["银杏村(秋季限定)"],
          evening: ["市区住宿"],
          walkLevel: "约8千步",
          transport: "包车",
          nearbyFood: "银杏村农家菜",
        },
        {
          label: "Day3",
          morning: ["国殇墓园"],
          afternoon: ["返程"],
          evening: [],
          walkLevel: "约3千步",
          transport: "打车",
          nearbyFood: "市区",
        },
      ],
    },
    packingList: [
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "泳衣", category: "clothing", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "薄外套", category: "clothing", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "保湿护肤品", category: "gear", required: false },
    ],
  },
  {
    id: "aershan",
    name: "阿尔山",
    province: "内蒙古",
    tagline: "火山天池，林海秘境",
    gradient: "from-blue-400 via-emerald-200 to-cyan-100",
    isNiche: true,
    destTypes: ["mountain", "nature"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["summer", "autumn", "winter"],
    bestTime: "6-8月(避暑) / 9-10月(金秋彩林)",
    duration: "3-4天",
    budget: "人均1800-2800元",
    transportHub: "阿尔山机场/乌兰浩特转车",
    coreTip: "景区面积大必须坐观光车，昼夜温差极大，无论什么季节都要带厚外套",
    funSpots: [
      {
        name: "阿尔山天池",
        tagline: "中国第三大火山天池",
        ticket: "含在森林公园套票内",
        duration: "1.5小时",
        bestTime: "晴天湖水澄澈无波",
        tips: "海拔1332米，湖水久旱不涸久雨不溢，无进出水口",
        priority: "must",
      },
      {
        name: "驼峰岭天池",
        tagline: "心形火山口蓝宝石湖",
        ticket: "含在森林公园套票内",
        duration: "2小时",
        bestTime: "清晨晨雾缭绕时",
        tips: "俯瞰视角最佳，秋季金黄落叶松环绕，出片率极高",
        priority: "must",
      },
      {
        name: "三潭峡",
        tagline: "哈拉哈河峡谷秘境",
        ticket: "含在森林公园套票内",
        duration: "1.5小时",
        bestTime: "夏季绿意最浓",
        tips: "卧牛潭、虎石潭、悦心潭三步一景，河水清凉可戏水",
        priority: "niche",
      },
    ],
    food: [
      {
        name: "东北铁锅炖",
        pricePerPerson: "50-80元",
        howToEat: "排骨/大鹅配玉米贴饼，铁锅慢炖，暖身管饱",
        pitfall: "分量极大，建议2人以上点一锅，避免浪费",
      },
      {
        name: "手把羊肉",
        pricePerPerson: "80-120元",
        howToEat: "清水煮羊肉，蘸韭菜花或盐，保留羊肉原香",
        pitfall: "肉质紧实，牙口不好慎点，趁热吃风味最佳",
      },
      {
        name: "大兴安岭菌汤",
        pricePerPerson: "30-50元",
        howToEat: "本地野生菌菇慢炖，鲜香浓郁，林区特色汤品",
        pitfall: "野生菌需彻底煮熟，切勿自行采摘野菌食用",
      },
    ],
    foodAreas: [
      {
        name: "阿尔山市区夜市",
        location: "阿尔山市区",
        bestTime: "晚餐/夜宵",
        direction: "东北菜、烧烤聚集，烟火气浓，性价比高",
      },
      {
        name: "天池服务区",
        location: "森林公园内",
        bestTime: "三餐",
        direction: "景区内补给点，选择不多但方便，价格略高于市区",
      },
    ],
    shopping: [
      {
        name: "阿尔山市区特产街",
        category: "old_street",
        duration: "1小时",
        highlight: "山野菌菇、蓝莓干、奶食品等林区特产",
        forWho: "伴手礼",
      },
    ],
    pitfalls: [
      { category: "general", content: "昼夜温差极大，夏季夜间也可能10℃以下，务必带厚外套" },
      { category: "traffic", content: "景区内禁止自驾，必须乘坐观光车，景点间距最远达40公里" },
      { category: "general", content: "春秋为防火期，林区严禁烟火，禁止吸烟与明火" },
      { category: "general", content: "冬季极寒可达-30℃以下，需专业防寒装备与防滑鞋" },
    ],
    itinerary: {
      easy: [
        {
          label: "Day1",
          morning: ["抵达阿尔山→市区休整"],
          afternoon: ["阿尔山火车站打卡→市区闲逛"],
          evening: ["市区晚餐+住宿"],
          walkLevel: "约4千步",
          transport: "打车/包车",
          nearbyFood: "市区夜市",
        },
        {
          label: "Day2",
          morning: ["森林公园→天池→三潭峡"],
          afternoon: ["石塘林→杜鹃湖"],
          evening: ["景区内住宿"],
          walkLevel: "约1万步",
          transport: "景区观光车",
          nearbyFood: "天池服务区",
        },
        {
          label: "Day3",
          morning: ["驼峰岭天池→大峡谷"],
          afternoon: ["返程"],
          evening: [],
          walkLevel: "约8千步",
          transport: "景区观光车",
          nearbyFood: "景区服务区",
        },
      ],
      intense: [
        {
          label: "Day1",
          morning: ["抵达→森林公园全天深度游"],
          afternoon: ["天池→三潭峡→石塘林→杜鹃湖"],
          evening: ["景区内住宿看星空"],
          walkLevel: "约1.3万步",
          transport: "景区观光车",
          nearbyFood: "景区服务区",
        },
        {
          label: "Day2",
          morning: ["驼峰岭天池→大峡谷"],
          afternoon: ["返程"],
          evening: [],
          walkLevel: "约7千步",
          transport: "景区观光车",
          nearbyFood: "市区",
        },
      ],
    },
    packingList: [
      { name: "厚外套/冲锋衣", category: "clothing", required: true },
      { name: "舒适徒步鞋", category: "clothing", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "保温杯", category: "gear", required: true },
      { name: "防蚊虫药", category: "medicine", required: false },
    ],
  },
  {
    id: "taxkorgan",
    name: "塔什库尔干",
    province: "新疆",
    tagline: "帕米尔高原雄鹰之乡",
    gradient: "from-indigo-400 via-sky-200 to-slate-100",
    isNiche: true,
    destTypes: ["mountain", "nature"],
    durationRange: "4-7d",
    budgetRange: "comfort",
    seasons: ["spring", "summer", "autumn"],
    bestTime: "5-6月(湖水湛蓝) / 9-10月(金草滩秋色)",
    duration: "3-4天",
    budget: "人均1500-2500元",
    transportHub: "喀什出发包车/自驾，喀什机场/火车站",
    coreTip: "必须提前办理边防证，高原平均海拔3000+，注意预防高反，昼夜温差极大",
    funSpots: [
      {
        name: "喀拉库勒湖",
        tagline: "慕士塔格峰下的高原圣湖",
        ticket: "45元",
        duration: "2小时",
        bestTime: "晴天上午湖水最蓝",
        tips: "背靠冰川之父慕士塔格峰，湖水随光线变色，风大注意保暖",
        priority: "must",
      },
      {
        name: "石头城+金草滩",
        tagline: "丝路古堡+湿地金滩",
        ticket: "帕米尔旅游区联票110元(含区间车)",
        duration: "半天",
        bestTime: "日出日落时分",
        tips: "石头城是丝路遗址，金草滩秋季金黄，拍雪山倒影绝美",
        priority: "must",
      },
      {
        name: "盘龙古道",
        tagline: "今日走过所有弯路",
        ticket: "免费",
        duration: "1小时",
        bestTime: "晴天光线好",
        tips: "600多个S弯，自驾需老司机，拍照注意避让车辆",
        priority: "niche",
      },
    ],
    food: [
      {
        name: "高原手抓羊肉",
        pricePerPerson: "60-100元",
        howToEat: "帕米尔高原羊肉清水煮制，蘸盐或洋葱，几乎无膻味",
        pitfall: "分量扎实，肉质紧实，趁热吃风味最佳",
      },
      {
        name: "塔吉克咸奶茶",
        pricePerPerson: "10-20元",
        howToEat: "砖茶加牛奶盐熬制，暖身抗高反，塔吉克族日常饮品",
        pitfall: "咸口风味，第一次喝可能不习惯，越品越香",
      },
      {
        name: "馕坑烤肉",
        pricePerPerson: "50-80元",
        howToEat: "馕坑焖烤羊肉，外焦里嫩，配馕食用风味绝佳",
        pitfall: "口感偏干，搭配奶茶或汤食用更佳",
      },
    ],
    foodAreas: [
      {
        name: "塔县县城主街",
        location: "塔什库尔干县城",
        bestTime: "三餐",
        direction: "本地餐厅聚集，新疆菜+塔吉克风味，选择丰富",
      },
      {
        name: "湖边毡房餐",
        location: "喀拉库勒湖周边",
        bestTime: "午餐",
        direction: "体验高原毡房餐，风景好但选择少，价格略高",
      },
    ],
    shopping: [
      {
        name: "塔县民族手工艺品店",
        category: "old_street",
        duration: "1小时",
        highlight: "塔吉克族刺绣、鹰笛、高原干果特产",
        forWho: "伴手礼/收藏",
      },
    ],
    pitfalls: [
      { category: "general", content: "必须提前在喀什办理边防证，写明塔什库尔干县，检查站必查" },
      { category: "general", content: "平均海拔3000米以上，提前预防高反，前两天避免剧烈运动" },
      { category: "traffic", content: "盘龙古道路弯多弯急，新手慎驾，注意避让对向车辆" },
      { category: "general", content: "昼夜温差极大，白天20℃夜间可能0℃以下，带足保暖衣物" },
    ],
    itinerary: {
      easy: [
        {
          label: "Day1",
          morning: ["喀什出发→白沙湖→喀拉库勒湖"],
          afternoon: ["慕士塔格峰观景→塔县县城入住"],
          evening: ["塔县晚餐+休整适应海拔"],
          walkLevel: "约3千步",
          transport: "包车/自驾",
          nearbyFood: "塔县县城",
        },
        {
          label: "Day2",
          morning: ["石头城日出→金草滩湿地"],
          afternoon: ["塔吉克族家访→县城闲逛"],
          evening: ["塔县住宿"],
          walkLevel: "约6千步",
          transport: "步行+打车",
          nearbyFood: "塔县县城/农家",
        },
        {
          label: "Day3",
          morning: ["盘龙古道打卡"],
          afternoon: ["返回喀什"],
          evening: [],
          walkLevel: "约2千步",
          transport: "包车/自驾",
          nearbyFood: "沿途乡镇",
        },
      ],
      intense: [
        {
          label: "Day1",
          morning: ["喀什→白沙湖→喀拉库勒湖→石头城"],
          afternoon: ["金草滩→塔县入住"],
          evening: ["塔县晚餐"],
          walkLevel: "约5千步",
          transport: "包车/自驾",
          nearbyFood: "塔县县城",
        },
        {
          label: "Day2",
          morning: ["盘龙古道→返程喀什"],
          afternoon: ["抵达喀什"],
          evening: [],
          walkLevel: "约3千步",
          transport: "包车/自驾",
          nearbyFood: "沿途",
        },
      ],
    },
    packingList: [
      { name: "厚羽绒服/冲锋衣", category: "clothing", required: true },
      { name: "氧气瓶", category: "medicine", required: true },
      { name: "防晒霜SPF50+", category: "gear", required: true },
      { name: "身份证+边防证", category: "docs", required: true },
      { name: "墨镜", category: "gear", required: true },
      { name: "保温杯", category: "gear", required: true },
      { name: "红景天(提前1周)", category: "medicine", required: false },
    ],
  },
  
];

// 合并所有城市
export const allCities: CityGuide[] = [
  ...([] as CityGuide[]), // 占位，会在 city-data.ts 中合并
];
