import type { CityGuide } from "./types";

// 小众秘境目的地
export const nicheCities: CityGuide[] = [
  {
    id: "yading",
    name: "稻城亚丁",
    province: "四川",
    tagline: "最后的香格里拉",
    gradient: "from-sky-400 via-indigo-200 to-green-200",
    isNiche: true,
    destTypes: ["mountain", "nature", "hiking"],
    durationRange: "4-7d",
    budgetRange: "luxury",
    seasons: ["autumn"],
    bestTime: "9-10月(秋色) / 5-6月(花海)",
    duration: "5-7天",
    budget: "人均3000-5000元",
    transportHub: "稻城亚丁机场/成都出发自驾",
    coreTip: "海拔4000米+，高反是最大挑战，前两天别剧烈运动",
    funSpots: [
      { name: "三神山(仙乃日/央迈勇/夏诺多吉)", tagline: "藏传佛教圣山", ticket: "146元+观光车120元", duration: "2天", bestTime: "10月秋色最绝", tips: "天气决定一切，预留2天以防天气不好", priority: "must" },
      { name: "牛奶海+五色海", tagline: "高原海子", ticket: "含在门票内", duration: "4-5小时(徒步)", bestTime: "上午天气好时", tips: "最后1公里坡度极陡，量力而行", priority: "must" },
      { name: "洛绒牛场", tagline: "雪山草甸", ticket: "含在门票内", duration: "2小时", bestTime: "上午光线好", tips: "观光车终点，徒步起点", priority: "niche" },
    ],
    food: [
      { name: "酥油茶", pricePerPerson: "5-10元", howToEat: "咸口暖身，高反缓解", pitfall: "第一次喝可能不习惯" },
      { name: "牦牛肉", pricePerPerson: "50-80元", howToEat: "风干和炖煮都试试", pitfall: "别在景区买，稻城县城更便宜" },
      { name: "青稞饼", pricePerPerson: "5-8元", howToEat: "蘸酥油茶吃，藏族主食", pitfall: "口感偏硬，配茶才好吃" },
    ],
    foodAreas: [
      { name: "香格里拉镇(日瓦)", location: "亚丁景区门口", bestTime: "三餐", direction: "景区补给大本营，选择不多但够吃" },
      { name: "稻城县城", location: "稻城县城", bestTime: "进山前/出山后", direction: "补给+美食，比镇上丰富" },
    ],
    shopping: [
      { name: "稻城县城", category: "old_street", duration: "1小时", highlight: "藏族手工艺品和特产", forWho: "淘货" },
    ],
    pitfalls: [
      { category: "general", content: "海拔4000米+，高反是真实威胁，红景天提前1周吃" },
      { category: "general", content: "昼夜温差极大，夏天白天20度晚上0度" },
      { category: "traffic", content: "从成都自驾需2天，路况复杂需老司机" },
      { category: "general", content: "紫外线极强，防晒霜SPF50+不够还需物理防晒" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["成都→康定(自驾)"], afternoon: ["康定休整适应海拔"], evening: ["康定住宿"], walkLevel: "约3千步", transport: "自驾", nearbyFood: "康定城区" },
        { label: "Day2", morning: ["康定→稻城"], afternoon: ["稻城休整"], evening: ["稻城县城"], walkLevel: "约3千步", transport: "自驾", nearbyFood: "稻城县城" },
        { label: "Day3", morning: ["亚丁景区→冲古寺→珍珠海"], afternoon: ["珍珠海→返回"], evening: ["香格里拉镇休息"], walkLevel: "约8千步", transport: "观光车+步行", nearbyFood: "镇上餐厅" },
        { label: "Day4", morning: ["洛绒牛场→牛奶海"], afternoon: ["五色海(体力允许)"], evening: ["返回稻城"], walkLevel: "约1.5万步", transport: "观光车+徒步", nearbyFood: "稻城县城" },
      ],
      intense: [
        { label: "Day1", morning: ["成都→新都桥(自驾)"], afternoon: ["新都桥→稻城"], evening: ["稻城县城"], walkLevel: "约2千步", transport: "自驾", nearbyFood: "稻城县城" },
        { label: "Day2", morning: ["亚丁短线(冲古寺+珍珠海)"], afternoon: ["适应海拔+休整"], evening: ["香格里拉镇"], walkLevel: "约6千步", transport: "观光车+步行", nearbyFood: "镇上餐厅" },
        { label: "Day3", morning: ["洛绒牛场→牛奶海→五色海"], afternoon: ["继续徒步或返回"], evening: ["稻城县城"], walkLevel: "约2万步", transport: "观光车+徒步", nearbyFood: "稻城县城" },
      ],
    },
    packingList: [
      { name: "厚羽绒服", category: "clothing", required: true },
      { name: "登山鞋", category: "clothing", required: true },
      { name: "氧气瓶", category: "medicine", required: true },
      { name: "红景天(提前1周)", category: "medicine", required: true },
      { name: "防晒霜SPF50+", category: "gear", required: true },
      { name: "墨镜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "登山杖", category: "gear", required: false },
    ],
  },
  {
    id: "zhaoxing",
    name: "肇兴侗寨",
    province: "贵州",
    tagline: "鼓楼之乡，时光慢递",
    gradient: "from-teal-300 via-emerald-200 to-amber-100",
    isNiche: true,
    destTypes: ["ethnic", "ancient_city", "nature"],
    durationRange: "4-7d",
    budgetRange: "budget",
    seasons: ["spring", "summer", "autumn"],
    bestTime: "4-10月",
    duration: "3-4天",
    budget: "人均600-1200元",
    transportHub: "从江站(高铁)/贵阳转车",
    coreTip: "这里没有商业化的喧嚣，请尊重当地侗族生活习惯",
    funSpots: [
      { name: "肇兴侗寨五座鼓楼", tagline: "世界最大侗族村寨", ticket: "80元", duration: "半天", bestTime: "清晨和傍晚最安静", tips: "每座鼓楼代表一个团，各有特色", priority: "must" },
      { name: "堂安梯田", tagline: "云端梯田", ticket: "免费", duration: "3-4小时", bestTime: "日出时分", tips: "从肇兴徒步上堂安约2小时，景色绝美", priority: "must" },
      { name: "侗族大歌表演", tagline: "世界非遗", ticket: "免费(定时演出)", duration: "1小时", bestTime: "晚上8点", tips: "多声部无指挥合唱，世界级非遗", priority: "must" },
    ],
    food: [
      { name: "酸汤鱼", pricePerPerson: "30-50元", howToEat: "红酸汤+稻花鱼，贵州灵魂", pitfall: "酸汤是发酵的，第一次可能不习惯" },
      { name: "油茶", pricePerPerson: "5-10元", howToEat: "茶叶+花生+米花+葱姜", pitfall: "侗族早餐标配，咸口" },
      { name: "糯米饭", pricePerPerson: "5-10元", howToEat: "手抓着吃，配酸汤或腌肉", pitfall: "很顶饱，别吃太多" },
    ],
    foodAreas: [
      { name: "寨内主街", location: "肇兴侗寨内", bestTime: "三餐", direction: "沿街小馆子，酸汤鱼为主" },
    ],
    shopping: [
      { name: "侗寨手工艺品", category: "old_street", duration: "1小时", highlight: "侗布、银饰、刺绣", forWho: "淘货/文艺" },
    ],
    pitfalls: [
      { category: "traffic", content: "从江高铁站到肇兴需转车约40分钟" },
      { category: "general", content: "尊重侗族风俗，鼓楼内不要大声喧哗" },
      { category: "general", content: "住宿条件较简陋，不要期待星级酒店" },
      { category: "general", content: "带现金，部分小店不支持电子支付" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["到达肇兴"], afternoon: ["寨内漫步+五座鼓楼"], evening: ["侗族大歌表演"], walkLevel: "约6千步", transport: "步行", nearbyFood: "寨内小馆" },
        { label: "Day2", morning: ["徒步堂安梯田(2小时上山)"], afternoon: ["堂安村午餐+梯田拍照"], evening: ["返回肇兴+油茶"], walkLevel: "约1.2万步", transport: "徒步", nearbyFood: "堂安农家" },
        { label: "Day3", morning: ["周边岜沙苗寨(可选)"], afternoon: ["返回肇兴"], evening: ["告别晚餐"], walkLevel: "约5千步", transport: "包车", nearbyFood: "寨内" },
      ],
      intense: [],
    },
    packingList: [
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "防蚊虫药", category: "medicine", required: true },
      { name: "雨衣", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "现金", category: "docs", required: true },
    ],
  },
  {
    id: "wuyuan",
    name: "婺源",
    province: "江西",
    tagline: "中国最美乡村，油菜花海",
    gradient: "from-yellow-300 via-green-200 to-sky-200",
    isNiche: true,
    destTypes: ["nature", "ancient_city"],
    durationRange: "4-7d",
    budgetRange: "budget",
    seasons: ["spring"],
    bestTime: "3月中旬-4月上旬(油菜花)",
    duration: "3-4天",
    budget: "人均800-1500元",
    transportHub: "婺源站(高铁)/景德镇转车",
    coreTip: "油菜花花期只有3周，3月中旬-4月初，错过再等一年",
    funSpots: [
      { name: "江岭梯田油菜花", tagline: "婺源最壮观的花海", ticket: "80元", duration: "3-4小时", bestTime: "清晨看云海+花海", tips: "是婺源赏花第一站，必须早起", priority: "must" },
      { name: "篁岭晒秋", tagline: "最美中国符号", ticket: "120元+索道", duration: "3-4小时", bestTime: "四季不同景", tips: "晒秋是秋景，春天看花，夏天看绿", priority: "must" },
      { name: "思溪延村", tagline: "徽派古村落", ticket: "60元", duration: "2小时", bestTime: "上午人少", tips: "《聊斋》取景地，古建筑精美", priority: "niche" },
    ],
    food: [
      { name: "荷包红鲤鱼", pricePerPerson: "30-50元", howToEat: "清蒸最鲜，婺源招牌菜", pitfall: "别买景区门口的，村里吃更实惠" },
      { name: "糊豆腐", pricePerPerson: "10-15元", howToEat: "徽菜经典，开胃又暖身", pitfall: "看似平淡实际很香" },
      { name: "清明果", pricePerPerson: "5-8元", howToEat: "艾草+糯米+馅料，春天限定", pitfall: "只有3-4月才有最正宗的" },
    ],
    foodAreas: [
      { name: "各村落农家乐", location: "景区内村落", bestTime: "午餐/晚餐", direction: "住在哪吃到哪，农家菜最实在" },
    ],
    shopping: [
      { name: "篁岭天街", category: "old_street", duration: "1-2小时", highlight: "徽派建筑+文创小店", forWho: "拍照/购物" },
    ],
    pitfalls: [
      { category: "general", content: "花期只有3周，务必提前查当年花期" },
      { category: "traffic", content: "各景点分散，建议自驾或包车" },
      { category: "general", content: "3月雨多带伞，花海配烟雨更有意境" },
      { category: "general", content: "住宿旺季涨价3倍+，提前1个月订" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["到达婺源→江岭梯田"], afternoon: ["江岭花海拍照"], evening: ["住江岭附近"], walkLevel: "约8千步", transport: "自驾/包车", nearbyFood: "农家乐" },
        { label: "Day2", morning: ["篁岭(索道上山)"], afternoon: ["篁岭天街+晒秋"], evening: ["住篁岭或县城"], walkLevel: "约1万步", transport: "索道+步行", nearbyFood: "篁岭天街" },
        { label: "Day3", morning: ["思溪延村"], afternoon: ["彩虹桥→返程"], evening: [""], walkLevel: "约6千步", transport: "自驾/包车", nearbyFood: "农家乐" },
      ],
      intense: [],
    },
    packingList: [
      { name: "雨衣/雨伞", category: "gear", required: true },
      { name: "舒适步行鞋", category: "clothing", required: true },
      { name: "防晒霜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
    ],
  },
  {
    id: "ejina",
    name: "额济纳",
    province: "内蒙古",
    tagline: "三千年的胡杨，三千年的守望",
    gradient: "from-amber-400 via-orange-300 to-red-300",
    isNiche: true,
    destTypes: ["nature", "hiking"],
    durationRange: "4-7d",
    budgetRange: "luxury",
    seasons: ["autumn"],
    bestTime: "10月1日-20日(胡杨林金秋)",
    duration: "4-5天",
    budget: "人均3000-5000元",
    transportHub: "额济纳旗机场/银川转车",
    coreTip: "胡杨林最佳观赏期只有20天，10月初-中旬，错过再等一年",
    funSpots: [
      { name: "额济纳胡杨林", tagline: "世界三大胡杨林之一", ticket: "240元(八道桥联票)", duration: "1天", bestTime: "10月1-15日", tips: "二道桥拍倒影，四道桥拍人像，七道桥最原始", priority: "must" },
      { name: "居延海日出", tagline: "沙漠中的海子", ticket: "60元", duration: "2-3小时", bestTime: "清晨6点看日出", tips: "必须早起！日出瞬间水面金色太美", priority: "must" },
      { name: "黑城遗址", tagline: "西夏古城废墟", ticket: "含在胡杨林联票", duration: "1-2小时", bestTime: "下午光线斜射", tips: "苍凉感十足，拍照极有氛围", priority: "niche" },
    ],
    food: [
      { name: "手把肉", pricePerPerson: "40-60元", howToEat: "手撕着吃，蘸蒜泥酱油", pitfall: "份量大，2人点1斤足够" },
      { name: "奶茶+奶皮子", pricePerPerson: "10-20元", howToEat: "咸奶茶配奶皮子，蒙古早餐", pitfall: "咸口奶茶，跟甜奶茶完全不同" },
      { name: "烤全羊", pricePerPerson: "人均80-120元", howToEat: "4人起吃，配蒙古包子", pitfall: "需提前3小时预定，不是随时有" },
    ],
    foodAreas: [
      { name: "达镇主街", location: "额济纳旗达来呼布镇", bestTime: "三餐", direction: "小镇不大，主街餐厅集中" },
    ],
    shopping: [
      { name: "达镇特产店", category: "old_street", duration: "30分钟", highlight: "肉苁蓉、锁阳等沙漠特产", forWho: "淘货" },
    ],
    pitfalls: [
      { category: "general", content: "最佳观赏期只有20天，务必提前查当年叶黄时间" },
      { category: "general", content: "住宿旺季一房难求且价格翻3倍+，提前2个月订" },
      { category: "general", content: "沙漠温差极大，白天25度晚上0度" },
      { category: "traffic", content: "距银川800公里自驾10小时，建议飞额济纳机场" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["到达额济纳"], afternoon: ["达镇休息适应"], evening: ["主街觅食"], walkLevel: "约3千步", transport: "飞机/自驾", nearbyFood: "达镇主街" },
        { label: "Day2", morning: ["胡杨林(二道桥-四道桥)"], afternoon: ["胡杨林(五道桥-七道桥)"], evening: ["八道桥看日落"], walkLevel: "约1.5万步", transport: "景区摆渡车+步行", nearbyFood: "自带干粮" },
        { label: "Day3", morning: ["居延海日出(5点出发)"], afternoon: ["黑城遗址"], evening: ["达镇晚餐"], walkLevel: "约8千步", transport: "包车", nearbyFood: "达镇主街" },
      ],
      intense: [],
    },
    packingList: [
      { name: "厚羽绒服", category: "clothing", required: true },
      { name: "保温杯", category: "gear", required: true },
      { name: "防晒霜+墨镜", category: "gear", required: true },
      { name: "身份证", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "零食干粮", category: "gear", required: true },
    ],
  },
  {
    id: "kanas",
    name: "喀纳斯",
    province: "新疆",
    tagline: "上帝的后花园",
    gradient: "from-emerald-400 via-teal-300 to-sky-300",
    isNiche: true,
    destTypes: ["nature", "mountain", "hiking"],
    durationRange: "8d+",
    budgetRange: "premium",
    seasons: ["autumn"],
    bestTime: "9月中旬-10月初(秋色)",
    duration: "5-7天",
    budget: "人均5000-8000元",
    transportHub: "阿勒泰机场/乌鲁木齐出发",
    coreTip: "9月秋色只有2周窗口期，务必提前查当年时间",
    funSpots: [
      { name: "喀纳斯湖", tagline: "神秘的高山湖泊", ticket: "185元(含区间车)", duration: "1天", bestTime: "9月秋色最美", tips: "三湾(卧龙湾/月亮湾/神仙湾)必徒步", priority: "must" },
      { name: "禾木村", tagline: "图瓦人村落", ticket: "60元+区间车52元", duration: "1-2天", bestTime: "清晨晨雾+9月秋色", tips: "住一晚看晨雾，人间仙境", priority: "must" },
      { name: "白哈巴", tagline: "西北第一村", ticket: "50元+区间车", duration: "半天", bestTime: "傍晚看日落", tips: "边防证在景区办，需带身份证", priority: "niche" },
    ],
    food: [
      { name: "大盘鸡", pricePerPerson: "40-60元", howToEat: "鸡肉+土豆+皮带面，新疆灵魂", pitfall: "2人点小盘，份量惊人" },
      { name: "手抓饭", pricePerPerson: "25-40元", howToEat: "羊肉+胡萝卜+洋葱焖饭", pitfall: "午饭才有，卖完即止" },
      { name: "烤羊肉串", pricePerPerson: "10-20元", howToEat: "肥瘦相间最香", pitfall: "景区比镇上贵1倍" },
    ],
    foodAreas: [
      { name: "贾登峪(景区门口)", location: "喀纳斯景区入口", bestTime: "三餐", direction: "补给大本营，选择有限" },
      { name: "禾木村内", location: "禾木村", bestTime: "三餐", direction: "图瓦人家庭旅馆+小餐馆" },
    ],
    shopping: [
      { name: "禾木村", category: "old_street", duration: "1小时", highlight: "图瓦人手工艺品", forWho: "淘货" },
    ],
    pitfalls: [
      { category: "general", content: "9月秋色窗口期只有2周，提前查时间" },
      { category: "general", content: "景区物价贵2-3倍，自带干粮很必要" },
      { category: "traffic", content: "乌鲁木齐到喀纳斯自驾10小时，建议飞阿勒泰" },
      { category: "general", content: "早晚温差20度+，四季衣服都带上" },
    ],
    itinerary: {
      easy: [
        { label: "Day1", morning: ["阿勒泰→贾登峪"], afternoon: ["入住休整"], evening: ["贾登峪晚餐"], walkLevel: "约2千步", transport: "包车", nearbyFood: "贾登峪" },
        { label: "Day2", morning: ["喀纳斯湖+三湾徒步"], afternoon: ["观鱼台俯瞰全湖"], evening: ["返回贾登峪"], walkLevel: "约1.5万步", transport: "区间车+步行", nearbyFood: "自带干粮" },
        { label: "Day3", morning: ["禾木村"], afternoon: ["禾木漫步+骑马"], evening: ["住禾木看星空"], walkLevel: "约8千步", transport: "区间车+步行", nearbyFood: "禾木村内" },
        { label: "Day4", morning: ["禾木晨雾(必看)"], afternoon: ["白哈巴(可选)"], evening: ["返回"], walkLevel: "约6千步", transport: "区间车", nearbyFood: "贾登峪" },
      ],
      intense: [],
    },
    packingList: [
      { name: "厚羽绒服", category: "clothing", required: true },
      { name: "登山鞋", category: "clothing", required: true },
      { name: "保温杯", category: "gear", required: true },
      { name: "防晒霜+墨镜", category: "gear", required: true },
      { name: "身份证(边防证用)", category: "docs", required: true },
      { name: "充电宝", category: "electronics", required: true },
      { name: "零食干粮", category: "gear", required: true },
    ],
  },
];

// 合并所有城市
export const allCities: CityGuide[] = [
  ...([] as CityGuide[]), // 占位，会在 city-data.ts 中合并
];
